export default {
  id: 'lift',
  title: 'The Third Floor',
  topic: 'ночная смена в пустом здании',
  genre: { id: 'horror', label: 'Ужастик', emoji: '🕯️' },
  imageStyle: 'moody cinematic film photograph, deep shadows, cold light, unsettling emptiness',
  imagePrompt: 'an empty office corridor at night seen from an open lift, one door glowing, cold light',
  paragraphs: [
    '**What if the safest place you know is the one you should never enter?** Marta had cleaned the old office building for eleven years. She knew the sound of every door and the smell of the floor polish. She knew that the heating pipes clicked twice at two in the morning, and that the third window on the second floor never closed properly. The building was empty after ten, and she liked it that way. Empty simply meant quiet, and quiet was easy to work in.',
    'The lift was the only thing she never trusted. It was old, with a brass handle and a small yellow light above the doors. Sometimes it moved between floors when nobody had called it. Marta always told herself the same thing: old buildings have old machines, and old machines make mistakes. She even wrote it in her notebook once, as if writing it down would make it true. Then she went back to her cart and finished the corridor.',
    'On Tuesday the lift stopped at the third floor at exactly one in the morning. Marta looked up from her bucket. The third floor had been closed since March, when the company moved out and took everything with them, even the light bulbs. She waited. The doors opened slowly, and the corridor beyond them was bright. Somebody had turned the lights on, and somebody had to be standing there to do it.',
    'She did not call security. She did not run. She stood very still and listened to the building she thought she knew, and the building said nothing at all. After a minute the doors closed again and the lift went down without her. Her hands were shaking, but she finished the floor, because the floor was her job and fear was not.',
    '**Marta took the stairs for the rest of that year. And every night, as she passed the third floor, she noticed the same thin line of light under the door — waiting, patient, already on.**',
  ],
  questions: [
    {
      question: 'How long had Marta worked in the building?',
      options: ['Two years', 'Six years', 'Eleven years', 'Twenty years'],
      correctIndex: 2,
      explanation: 'В первом абзаце: «Marta had cleaned the old office building for eleven years».',
    },
    {
      question: 'Why did Marta not trust the lift?',
      options: [
        'It was very slow',
        'It sometimes moved when nobody called it',
        'It was too small',
        'It made a loud noise',
      ],
      correctIndex: 1,
      explanation: 'Во втором абзаце: лифт иногда двигался между этажами, хотя его никто не вызывал.',
    },
    {
      question: 'Why was the light on the third floor strange?',
      options: [
        'The floor had been empty since March',
        'The lights were usually red',
        'It was daytime',
        'The floor was being repaired',
      ],
      correctIndex: 0,
      explanation: 'Этаж пустовал с марта, оттуда вынесли даже лампочки — значит, свет включил кто-то живой.',
    },
    {
      question: 'What does the last paragraph suggest?',
      options: [
        'The problem was solved',
        'Marta found a new job',
        'Somebody is still up there',
        'The lift was repaired',
      ],
      correctIndex: 2,
      explanation: 'Свет под дверью горит каждую ночь — то, что было там, никуда не делось.',
    },
  ],
  keyPoints: [
    'Марта много лет убирала старое офисное здание по ночам и знала там каждый звук.',
    'Она не доверяла старому лифту: он иногда ездил сам по себе.',
    'Однажды ночью лифт остановился на третьем этаже, который пустовал с марта.',
    'Двери открылись — в пустом коридоре горел свет, значит там кто-то был.',
    'Марта не убежала, доработала смену, но с тех пор ходила по лестнице — и свет горел каждую ночь.',
  ],
  modelRetelling:
    'The story is about Marta, a cleaner who worked at night in an old office building for eleven years. She knew every sound in the building, but she never trusted the old lift, because it sometimes moved on its own. One night the lift stopped at the third floor, which had been empty since March. The doors opened and the corridor was bright — somebody had turned the lights on. Marta stayed calm and finished her work, but after that night she always took the stairs, and the light was always on.',
  discussion: [
    'Have you ever been alone in a big empty building? How did it feel?',
    'Marta stayed and finished her work. Would you have done the same, or would you have left?',
    'Do you enjoy scary stories, or do you prefer something calmer? Why?',
    'Some people say old buildings have their own character. Do you agree?',
  ],
  phrases: [
    { en: 'It made me feel uneasy.', ru: 'Мне стало не по себе.' },
    { en: 'I would probably have left immediately.', ru: 'Я бы, наверное, сразу ушёл.' },
    { en: 'To be honest, I am not a brave person.', ru: 'Честно говоря, я не храбрый человек.' },
    { en: 'It reminds me of a time when…', ru: 'Это напоминает мне случай, когда…' },
  ],
  glossary: {
    safest: { t: 'самый безопасный', l: 'safe', p: 'прил.' },
    place: { t: 'место', p: 'сущ.' },
    know: { t: 'знать', p: 'глаг.' },
    never: { t: 'никогда', p: 'нареч.' },
    enter: { t: 'входить', p: 'глаг.' },
    cleaned: { t: 'убирала', l: 'clean', p: 'глаг.' },
    office: { t: 'офисный', p: 'прил.' },
    building: { t: 'здание', p: 'сущ.' },
    eleven: { t: 'одиннадцать', p: 'числ.' },
    years: { t: 'лет', l: 'year', p: 'сущ.' },
    knew: { t: 'знала', l: 'know', p: 'глаг.' },
    sound: { t: 'звук', p: 'сущ.' },
    every: { t: 'каждый', p: 'мест.' },
    door: { t: 'дверь', p: 'сущ.' },
    smell: { t: 'запах', p: 'сущ.' },
    floor: { t: 'пол; этаж', p: 'сущ.', n: 'здесь и «пол», и «этаж» — смотрите по фразе' },
    polish: { t: 'полироль, мастика', p: 'сущ.' },
    heating: { t: 'отопительный', p: 'прил.' },
    pipes: { t: 'трубы', l: 'pipe', p: 'сущ.' },
    clicked: { t: 'щёлкали', l: 'click', p: 'глаг.' },
    twice: { t: 'дважды', p: 'нареч.' },
    morning: { t: 'утро', p: 'сущ.' },
    third: { t: 'третий', p: 'числ.' },
    window: { t: 'окно', p: 'сущ.' },
    second: { t: 'второй', p: 'числ.' },
    closed: { t: 'закрывалось; закрыт', l: 'close', p: 'глаг.' },
    properly: { t: 'как следует', p: 'нареч.' },
    empty: { t: 'пустой', p: 'прил.' },
    after: { t: 'после', p: 'предл.' },
    ten: { t: 'десять', p: 'числ.' },
    liked: { t: 'нравилось', l: 'like', p: 'глаг.' },
    way: { t: 'способ; путь', p: 'сущ.', n: 'в «that way» — «именно так»' },
    simply: { t: 'просто', p: 'нареч.' },
    meant: { t: 'означало', l: 'mean', p: 'глаг.' },
    quiet: { t: 'тишина; тихий', p: 'сущ./прил.' },
    easy: { t: 'легко, простой', p: 'прил.' },
    work: { t: 'работать; работа', p: 'глаг./сущ.' },
    lift: { t: 'лифт', p: 'сущ.', n: 'британский вариант; в США — elevator' },
    only: { t: 'единственный; только', p: 'прил./нареч.' },
    thing: { t: 'вещь, штука', p: 'сущ.' },
    trusted: { t: 'доверяла', l: 'trust', p: 'глаг.' },
    old: { t: 'старый', p: 'прил.' },
    brass: { t: 'латунный', p: 'прил.' },
    handle: { t: 'ручка', p: 'сущ.' },
    small: { t: 'маленький', p: 'прил.' },
    yellow: { t: 'жёлтый', p: 'прил.' },
    light: { t: 'свет; лампочка', p: 'сущ.' },
    above: { t: 'над', p: 'предл.' },
    doors: { t: 'двери', l: 'door', p: 'сущ.' },
    sometimes: { t: 'иногда', p: 'нареч.' },
    moved: { t: 'двигался', l: 'move', p: 'глаг.' },
    between: { t: 'между', p: 'предл.' },
    floors: { t: 'этажи', l: 'floor', p: 'сущ.' },
    nobody: { t: 'никто', p: 'мест.' },
    called: { t: 'вызывал', l: 'call', p: 'глаг.' },
    always: { t: 'всегда', p: 'нареч.' },
    told: { t: 'говорила', l: 'tell', p: 'глаг.' },
    herself: { t: 'себе, сама', p: 'мест.' },
    same: { t: 'тот же самый', p: 'прил.' },
    buildings: { t: 'здания', l: 'building', p: 'сущ.' },
    machines: { t: 'механизмы, машины', l: 'machine', p: 'сущ.' },
    make: { t: 'делать; совершать', p: 'глаг.' },
    mistakes: { t: 'ошибки', l: 'mistake', p: 'сущ.' },
    even: { t: 'даже', p: 'нареч.' },
    wrote: { t: 'написала', l: 'write', p: 'глаг.' },
    notebook: { t: 'блокнот', p: 'сущ.' },
    once: { t: 'однажды', p: 'нареч.' },
    writing: { t: 'записывание', l: 'write', p: 'глаг.' },
    down: { t: 'вниз', p: 'нареч.', n: 'write down — записать' },
    would: { t: 'бы', p: 'глаг.' },
    true: { t: 'правда, правдивый', p: 'прил.' },
    went: { t: 'пошла', l: 'go', p: 'глаг.' },
    back: { t: 'обратно', p: 'нареч.' },
    cart: { t: 'тележка', p: 'сущ.' },
    finished: { t: 'закончила', l: 'finish', p: 'глаг.' },
    corridor: { t: 'коридор', p: 'сущ.' },
    tuesday: { t: 'вторник', p: 'сущ.' },
    stopped: { t: 'остановился', l: 'stop', p: 'глаг.' },
    exactly: { t: 'ровно, точно', p: 'нареч.' },
    looked: { t: 'посмотрела', l: 'look', p: 'глаг.' },
    bucket: { t: 'ведро', p: 'сущ.' },
    been: { t: 'быть', l: 'be', p: 'глаг.' },
    since: { t: 'с (какого-то времени)', p: 'предл.' },
    march: { t: 'март', p: 'сущ.' },
    company: { t: 'компания', p: 'сущ.' },
    everything: { t: 'всё', p: 'мест.' },
    bulbs: { t: 'лампочки', l: 'bulb', p: 'сущ.' },
    waited: { t: 'ждала', l: 'wait', p: 'глаг.' },
    opened: { t: 'открылись', l: 'open', p: 'глаг.' },
    slowly: { t: 'медленно', p: 'нареч.' },
    beyond: { t: 'за (пределами)', p: 'предл.' },
    bright: { t: 'ярко освещённый', p: 'прил.' },
    somebody: { t: 'кто-то', p: 'мест.' },
    turned: { t: 'включил', l: 'turn', p: 'глаг.', n: 'turn on — включить' },
    lights: { t: 'свет, лампы', l: 'light', p: 'сущ.' },
    standing: { t: 'стоять', l: 'stand', p: 'глаг.' },
    security: { t: 'охрана', p: 'сущ.' },
    run: { t: 'бежать', p: 'глаг.' },
    stood: { t: 'стояла', l: 'stand', p: 'глаг.' },
    still: { t: 'неподвижно', p: 'нареч.', n: 'stand still — стоять не шевелясь' },
    listened: { t: 'слушала', l: 'listen', p: 'глаг.' },
    thought: { t: 'думала', l: 'think', p: 'глаг.' },
    said: { t: 'сказало', l: 'say', p: 'глаг.' },
    nothing: { t: 'ничего', p: 'мест.' },
    minute: { t: 'минута', p: 'сущ.' },
    again: { t: 'снова', p: 'нареч.' },
    without: { t: 'без', p: 'предл.' },
    hands: { t: 'руки', l: 'hand', p: 'сущ.' },
    shaking: { t: 'дрожали', l: 'shake', p: 'глаг.' },
    because: { t: 'потому что', p: 'союз' },
    job: { t: 'работа', p: 'сущ.' },
    fear: { t: 'страх', p: 'сущ.' },
    took: { t: 'ходила (по лестнице)', l: 'take', p: 'глаг.', n: 'take the stairs — идти по лестнице' },
    stairs: { t: 'лестница', p: 'сущ.' },
    rest: { t: 'остаток', p: 'сущ.', n: 'the rest of the year — остаток года' },
    year: { t: 'год', p: 'сущ.' },
    night: { t: 'ночь', p: 'сущ.' },
    passed: { t: 'проходила мимо', l: 'pass', p: 'глаг.' },
    noticed: { t: 'замечала', l: 'notice', p: 'глаг.' },
    thin: { t: 'тонкий', p: 'прил.' },
    line: { t: 'полоска, линия', p: 'сущ.' },
    under: { t: 'под', p: 'предл.' },
    waiting: { t: 'ждущий', l: 'wait', p: 'глаг.' },
    patient: { t: 'терпеливый', p: 'прил.' },
    already: { t: 'уже', p: 'нареч.' },
  },
};
