/** Тексты 26–30. */
export default [
  {
    id: 'museum-night',
    title: 'Night Shift at the Museum',
    topic: 'ночное дежурство среди экспонатов',
    genre: { id: 'horror', label: 'Ужастик', emoji: '🕯️' },
    imagePrompt: 'a dark museum hall at night, glass cases, one torch beam on a stone figure',
    paragraphs: [
      '**The rule at the museum was simple and everybody laughed about it: on the night round, do not use the lights in Hall Four.** New guards were told to use a torch there instead, because the ceiling lamps were old and switching them on had once caused a small fire. That was the official reason, printed on a card by the door, and Nikita had no reason to doubt it for the first three weeks.',
      'Hall Four held the stone figures: nine of them, brought from a dig in the south in 1961, each about a metre high, arranged in a wide circle facing outwards. In daylight they were interesting and a little ugly. At two in the morning, with a torch, they were simply nine shapes that your eye kept counting because counting them was somehow easier than not counting them.',
      'On his nineteenth night Nikita made a mistake with the switches and the ceiling lights came on for perhaps four seconds. The figures stood exactly where they always stood. He remembers thinking, with relief, that this was the whole joke, that generations of guards had frightened each other over nothing. Then the lights went out again and he walked on with the torch.',
      'He completed the round, wrote the time in the book at 02:41, and went back to the desk. It was only when he was drinking his tea that his hand stopped, because he had seen the circle twice that night and something in the second picture had been different, and it took him another eleven minutes to work out what: under the ceiling lights, the nine figures had been facing inwards.',
      '**Nikita finished the month and left. He never told anybody the real reason, and he has never in his life explained why he now dislikes standing in the middle of a room.**',
    ],
    questions: [
      {
        question: 'What was the rule about Hall Four?',
        options: [
          'Do not go there at night',
          'Do not use the ceiling lights, use a torch',
          'Always go there with a colleague',
          'Do not touch the glass cases',
        ],
        correctIndex: 1,
        explanation: 'Потолочный свет включать нельзя — велено пользоваться фонарём.',
      },
      {
        question: 'What was in Hall Four?',
        options: [
          'Nine stone figures in a circle',
          'Paintings from the south',
          'Old machines',
          'The museum archive',
        ],
        correctIndex: 0,
        explanation: 'Девять каменных фигур, расставленных по кругу.',
      },
      {
        question: 'What happened on his nineteenth night?',
        options: [
          'The lights came on for a few seconds by mistake',
          'A figure fell over',
          'He heard footsteps',
          'The door was locked',
        ],
        correctIndex: 0,
        explanation: 'Он перепутал выключатели, и потолочный свет горел секунды четыре.',
      },
      {
        question: 'What did he realise later?',
        options: [
          'One figure was missing',
          'Under the ceiling lights the figures faced inwards',
          'The lights had started a fire',
          'He had forgotten to sign the book',
        ],
        correctIndex: 1,
        explanation: 'При включённом свете фигуры стояли лицом внутрь круга, а не наружу.',
      },
    ],
    keyPoints: [
      'В музее было правило: в четвёртом зале не включать потолочный свет, только фонарь.',
      'В зале стояли девять каменных фигур по кругу, лицом наружу.',
      'На девятнадцатую ночь Никита случайно включил свет на несколько секунд.',
      'Сначала он решил, что всё это просто байка для новичков.',
      'За чаем он понял: при свете фигуры стояли лицом внутрь круга.',
    ],
    modelRetelling:
      'A night guard worked in a museum where there was a strange rule: in Hall Four you must use a torch and never switch on the ceiling lights. The hall contained nine stone figures standing in a circle. One night the guard turned the lights on by mistake for a few seconds and thought everything looked normal. Later, drinking his tea, he understood that under the ceiling lights the figures had been facing inwards, not outwards. He left the job that month.',
    discussion: [
      'Would you take a job as a night guard? Why or why not?',
      'Are there places in your town that feel strange at night?',
      'Do you prefer horror that explains everything or leaves questions?',
    ],
    glossary: {
      shift: { t: 'смена' },
      round: { t: 'обход' },
      hall: { t: 'зал' },
      guards: { t: 'охранники', l: 'guard' },
      torch: { t: 'фонарь' },
      ceiling: { t: 'потолок' },
      lamps: { t: 'лампы', l: 'lamp' },
      switching: { t: 'включение', l: 'switch' },
      official: { t: 'официальный' },
      doubt: { t: 'сомневаться' },
      figures: { t: 'фигуры', l: 'figure' },
      dig: { t: 'раскопки' },
      arranged: { t: 'расставлены', l: 'arrange' },
      circle: { t: 'круг' },
      outwards: { t: 'наружу' },
      inwards: { t: 'внутрь' },
      daylight: { t: 'дневной свет' },
      ugly: { t: 'уродливый' },
      shapes: { t: 'силуэты', l: 'shape' },
      switches: { t: 'выключатели', l: 'switch' },
      relief: { t: 'облегчение' },
      generations: { t: 'поколения', l: 'generation' },
      frightened: { t: 'пугали', l: 'frighten' },
      completed: { t: 'закончил', l: 'complete' },
      dislikes: { t: 'не любит', l: 'dislike' },
    },
  },

  {
    id: 'ring-drain',
    title: 'The Ring in the Drain',
    topic: 'кольцо, найденное в отеле',
    genre: { id: 'mystery', label: 'Детектив', emoji: '🔎' },
    imagePrompt: 'a hotel bathroom sink with a gold ring beside the drain, noir lighting',
    paragraphs: [
      '**The plumber found it, the manager reported it, and everybody agreed it was a lucky ending until somebody looked at the dates.** A wedding ring had been lost in room 210 of the Hotel Kama in April, and a woman named Irina Sokolova had claimed nine hundred euros from the hotel insurance for it. In September a plumber cleaning the drain pulled out the ring, undamaged, with the initials still readable inside.',
      'The hotel was pleased, and said so in a short message to the local paper about honesty and good service. The insurance company was less pleased, and sent a quiet man named Beketov, who liked drains, disliked coincidences, and had spent nine years learning that objects rarely lie but people frequently arrange them. He asked for the plumbing plan of the floor, the cleaning schedule and, oddly, the record of which rooms had been redecorated that summer.',
      'Room 210 had been redecorated in June, and that included replacing the pipe under the sink. A ring lost in April, sitting in the old pipe, would have gone into a builder\'s skip in June with the pipe around it. The ring that came out in September had been in a pipe that was three months younger than the loss it was supposed to explain.',
      'Beketov did not say any of this to Irina Sokolova. He said it to the hotel, because a guest cannot open a wall or choose a plumber, and because the claim had been paid to an account that also received payments from the hotel\'s maintenance budget. Two people lost their jobs, and one of them was the person who had first suggested checking the drain.',
      '**People imagine that an investigation is about finding the object. Usually the object is not the problem. The problem is that objects, unlike people, cannot be in two times at once.**',
    ],
    questions: [
      {
        question: 'What was found in the drain?',
        options: ['A key', 'A wedding ring', 'A phone', 'Money'],
        correctIndex: 1,
        explanation: 'Сантехник вытащил из слива обручальное кольцо с читаемыми инициалами.',
      },
      {
        question: 'Why did Beketov ask about redecoration?',
        options: [
          'He wanted to book a room',
          'To find out whether the pipe had been replaced',
          'He suspected the decorator',
          'The hotel asked him to',
        ],
        correctIndex: 1,
        explanation: 'Он выяснял, меняли ли трубу под раковиной.',
      },
      {
        question: 'Why is the timing impossible?',
        options: [
          'The ring was too new',
          'The pipe was replaced in June, after the loss in April',
          'The hotel was closed in April',
          'The plumber worked there only in July',
        ],
        correctIndex: 1,
        explanation: 'Кольцо, потерянное в апреле, уехало бы вместе со старой трубой в июне.',
      },
      {
        question: 'Who did Beketov suspect in the end?',
        options: [
          'The guest',
          'People inside the hotel',
          'The plumber alone',
          'The insurance company',
        ],
        correctIndex: 1,
        explanation: 'Гость не может вскрыть стену и выбрать сантехника, а выплата шла на счёт, связанный с отелем.',
      },
    ],
    keyPoints: [
      'В апреле в номере 210 пропало обручальное кольцо, и по страховке выплатили девятьсот евро.',
      'В сентябре сантехник достал кольцо из слива, целое и с инициалами.',
      'Страховой агент Бекетов запросил план труб, график уборки и список ремонтов.',
      'Номер отремонтировали в июне, заменив трубу под раковиной, — кольцо из апреля не могло там лежать.',
      'Подозрение легло не на гостью, а на сотрудников отеля: выплата шла на связанный с отелем счёт.',
    ],
    modelRetelling:
      'A wedding ring was lost in a hotel room in April, and the guest received nine hundred euros from the insurance. In September a plumber found the ring in the drain. An investigator asked about repairs and learned that the pipe under the sink had been replaced in June. This meant the ring could not have been lying there since April. He decided that people working in the hotel, not the guest, had arranged it, because the money went to an account connected with the hotel.',
    discussion: [
      'Do you find this kind of "small detail" mystery interesting?',
      'Have you ever lost something valuable in a hotel or a taxi?',
      'What would you have checked first in this case?',
    ],
    glossary: {
      plumber: { t: 'сантехник' },
      drain: { t: 'слив' },
      lucky: { t: 'удачный' },
      wedding: { t: 'свадебный', n: 'wedding ring — обручальное кольцо' },
      ring: { t: 'кольцо' },
      claimed: { t: 'потребовала (по страховке)', l: 'claim' },
      euros: { t: 'евро' },
      undamaged: { t: 'целый' },
      initials: { t: 'инициалы' },
      readable: { t: 'читаемый' },
      pleased: { t: 'довольный' },
      coincidences: { t: 'совпадения', l: 'coincidence' },
      plumbing: { t: 'водопровод' },
      plan: { t: 'схема, план' },
      schedule: { t: 'график' },
      oddly: { t: 'странным образом' },
      record: { t: 'запись, учёт' },
      redecorated: { t: 'отремонтирован', l: 'redecorate' },
      replacing: { t: 'замена', l: 'replace' },
      pipe: { t: 'труба' },
      sink: { t: 'раковина' },
      skip: { t: 'мусорный контейнер' },
      claim: { t: 'требование выплаты' },
      account: { t: 'счёт' },
      maintenance: { t: 'обслуживание' },
      budget: { t: 'бюджет' },
      investigation: { t: 'расследование' },
    },
  },

  {
    id: 'between-floors',
    title: 'Between Floors',
    topic: 'лифт, застрявший в неудачный момент',
    genre: { id: 'thriller', label: 'Триллер', emoji: '⏱️' },
    imagePrompt: 'the inside of a stopped lift with emergency light, a phone screen glowing',
    paragraphs: [
      '**The lift stopped between the fourth and fifth floors at 19:12, which was eighteen minutes before Katya was supposed to give evidence.** She pressed the alarm and heard it ring somewhere far below. The emergency light came on, small and orange. Her phone had one bar and forty per cent, and the first message she sent was not to her husband but to the lawyer: I am in the building. I am stuck.',
      'The lawyer answered immediately with a single line: do not tell anyone which lift. Katya read it four times. Until that moment she had been annoyed, calculating whether the hearing would be moved to another day. After that line she was something else, and she sat down on the floor with her back against the wall and her bag against her chest.',
      'At 19:20 somebody knocked twice on the doors from outside, in a friendly rhythm, and a man\'s voice said that maintenance was on the way and asked her to confirm her name. Katya did not answer. The voice asked again, patiently, using her name anyway, and then said something to another person that she could not hear, and the knocking stopped.',
      'The fire service opened the doors at 19:52 with two men in helmets and a woman from the building who kept apologising. In the corridor there was nobody. The maintenance company said that no engineer had been sent, because no alarm had reached them: somebody had reset the panel on the ground floor at 19:14 and again at 19:31.',
      '**Katya gave her evidence four days later, in a different building, with a different lift she took twice on purpose before the hearing. Nothing was ever proved. But she still, out of habit, sends one person a message before she steps into a small metal room.**',
    ],
    questions: [
      {
        question: 'Why was the timing of the lift stopping important?',
        options: [
          'She was late for work',
          'She was about to give evidence',
          'The building was closing',
          'Her phone was dying',
        ],
        correctIndex: 1,
        explanation: 'До дачи показаний оставалось восемнадцать минут.',
      },
      {
        question: 'What did the lawyer tell her?',
        options: [
          'To call the police',
          'Not to tell anyone which lift she was in',
          'To wait quietly',
          'To press the alarm again',
        ],
        correctIndex: 1,
        explanation: 'Одна строка: не говори никому, в каком ты лифте.',
      },
      {
        question: 'What was strange about the man outside the doors?',
        options: [
          'He knew her name and asked her to confirm it',
          'He was singing',
          'He tried to open the doors',
          'He spoke another language',
        ],
        correctIndex: 0,
        explanation: 'Он просил подтвердить имя, а потом всё равно назвал его сам.',
      },
      {
        question: 'What did the maintenance company say afterwards?',
        options: [
          'They had sent an engineer',
          'No alarm had reached them, and the panel had been reset twice',
          'The lift was working normally',
          'The building had no maintenance contract',
        ],
        correctIndex: 1,
        explanation: 'Сигнал до них не дошёл: панель на первом этаже дважды сбрасывали.',
      },
    ],
    keyPoints: [
      'Лифт застрял между этажами за восемнадцать минут до дачи показаний Кати.',
      'Адвокат ответил одной строкой: никому не говори, в каком ты лифте.',
      'Снаружи постучали, мужской голос просил подтвердить её имя и всё равно назвал его.',
      'Пожарные открыли двери через сорок минут, в коридоре никого не было.',
      'Выяснилось, что сигнал тревоги не дошёл: панель на первом этаже дважды сбрасывали.',
    ],
    modelRetelling:
      'A woman was going to give evidence when the lift stopped between floors. She wrote to her lawyer, who told her not to say which lift she was in. Then a man knocked on the doors and asked her to confirm her name, but she stayed silent, and he went away. The fire service opened the lift forty minutes later and the corridor was empty. The maintenance company had received no alarm, because somebody had reset the panel downstairs twice.',
    discussion: [
      'Are you comfortable in lifts, or do you avoid them?',
      'What would you have done in Katya\'s place?',
      'Do you tell somebody where you are when you go somewhere alone?',
    ],
    glossary: {
      evidence: { t: 'показания' },
      pressed: { t: 'нажала', l: 'press' },
      alarm: { t: 'тревога, кнопка вызова' },
      emergency: { t: 'аварийный' },
      orange: { t: 'оранжевый' },
      bar: { t: 'деление (связи)' },
      lawyer: { t: 'адвокат' },
      stuck: { t: 'застряла', l: 'stick' },
      annoyed: { t: 'раздражена' },
      calculating: { t: 'прикидывая', l: 'calculate' },
      hearing: { t: 'слушание' },
      chest: { t: 'грудь' },
      knocked: { t: 'постучал', l: 'knock' },
      rhythm: { t: 'ритм' },
      maintenance: { t: 'техобслуживание' },
      confirm: { t: 'подтвердить' },
      patiently: { t: 'терпеливо' },
      helmets: { t: 'каски', l: 'helmet' },
      apologising: { t: 'извиняясь', l: 'apologise' },
      engineer: { t: 'инженер, мастер' },
      reset: { t: 'сбросил' },
      panel: { t: 'панель, щиток' },
      proved: { t: 'доказано', l: 'prove' },
      habit: { t: 'привычка' },
      metal: { t: 'металлический' },
    },
  },

  {
    id: 'letters-herself',
    title: 'Letters From Herself',
    topic: 'письма с датой из следующего года',
    genre: { id: 'weird', label: 'Странное', emoji: '🌀' },
    imagePrompt: 'a wooden letterbox with one white envelope, quiet street, dreamlike morning light',
    paragraphs: [
      '**The first letter arrived in March, in her own handwriting, dated the fourteenth of the following year.** Zoya read it standing by the letterbox. It said that the kitchen tap would start leaking in April and that the man who came to fix it would try to sell her a new boiler, and that she should say no. It was signed with her name and finished with a line she did use in letters: "Do not worry, it is only me."',
      'In April the tap leaked. The man offered her a boiler. She said no, and then sat in the kitchen for a long time, because until that moment she had been able to think of the letter as a joke by somebody who knew her handwriting well. The second letter came in June and was about her sister\'s health, and it was right too, and it was kind.',
      'She wrote back, of course. There was no address, so she posted the reply to her own flat, and it arrived the next day, unopened and unchanged, which she had somehow expected. After that she stopped trying to answer and simply waited, and the letters came about every eight weeks, and none of them ever mentioned anything that Zoya could not have survived.',
      'That last part was what she thought about most. Whoever was writing had chosen carefully: no lottery numbers, no accidents, nothing large. Only a leaking tap, a doctor\'s appointment, a friend who needed a call in November. It was not the future being revealed to her. It was somebody making sure that a woman living alone got a few small things right.',
      '**In the last letter, which came in December, the handwriting was shakier. It said that this was the final one, that everything important had been covered, and that she should stop reading the post so early in the morning, because the cold in that hallway was exactly how the trouble had started.**',
    ],
    questions: [
      {
        question: 'What was strange about the letters?',
        options: [
          'They had no words',
          'They were in her own handwriting and dated next year',
          'They came from another country',
          'They were written in a foreign language',
        ],
        correctIndex: 1,
        explanation: 'Её собственный почерк и дата из следующего года.',
      },
      {
        question: 'What did the first letter tell her?',
        options: [
          'To move house',
          'That the tap would leak and to refuse a new boiler',
          'To visit her sister',
          'To change her job',
        ],
        correctIndex: 1,
        explanation: 'Кран потечёт, мастер будет продавать бойлер — откажись.',
      },
      {
        question: 'What happened when she wrote a reply?',
        options: [
          'It never arrived',
          'It came back to her flat unopened',
          'She received an answer at once',
          'The postman refused to take it',
        ],
        correctIndex: 1,
        explanation: 'Письмо пришло на следующий день к ней же, нераспечатанным.',
      },
      {
        question: 'What did Zoya notice about the contents?',
        options: [
          'They were always about money',
          'They only mentioned small things she could survive',
          'They were frightening',
          'They repeated each other',
        ],
        correctIndex: 1,
        explanation: 'Ни лотерей, ни катастроф — только мелочи, которые можно пережить.',
      },
    ],
    keyPoints: [
      'Зоя стала получать письма своим почерком, датированные следующим годом.',
      'Первое предупредило про течь крана и мастера, который будет навязывать бойлер.',
      'Всё сбывалось, а ответное письмо вернулось к ней же нераспечатанным.',
      'В письмах никогда не было ничего крупного — только мелочи, которые она переживёт.',
      'Последнее письмо, написанное дрожащим почерком, попросило не читать почту рано утром в холодной прихожей.',
    ],
    modelRetelling:
      'A woman began to receive letters written in her own handwriting and dated the next year. The first one warned her that her tap would leak and that she should refuse a new boiler, and it was correct. More letters came, always about small things: her sister\'s health, a friend who needed a call. When she tried to reply, her letter came back to her own flat unopened. The last letter said it was the final one and asked her not to read the post in the cold hallway.',
    discussion: [
      'If you could send one short letter to yourself a year ago, what would it say?',
      'Would you want to know small things about your future?',
      'Why do you think the letters never mentioned anything big?',
    ],
    glossary: {
      handwriting: { t: 'почерк' },
      dated: { t: 'датированный', l: 'date' },
      letterbox: { t: 'почтовый ящик' },
      tap: { t: 'кран' },
      leaking: { t: 'протекать', l: 'leak' },
      boiler: { t: 'бойлер, котёл' },
      signed: { t: 'подписано', l: 'sign' },
      offered: { t: 'предложил', l: 'offer' },
      joke: { t: 'шутка' },
      health: { t: 'здоровье' },
      posted: { t: 'отправила', l: 'post' },
      reply: { t: 'ответ' },
      unopened: { t: 'нераспечатанный' },
      unchanged: { t: 'неизменённый' },
      expected: { t: 'ожидала', l: 'expect' },
      mentioned: { t: 'упоминало', l: 'mention' },
      survived: { t: 'пережила', l: 'survive' },
      lottery: { t: 'лотерея' },
      accidents: { t: 'несчастные случаи', l: 'accident' },
      appointment: { t: 'приём (у врача)' },
      revealed: { t: 'раскрыт', l: 'reveal' },
      shakier: { t: 'более дрожащий', l: 'shaky' },
      final: { t: 'последний' },
      covered: { t: 'охвачено', l: 'cover' },
      hallway: { t: 'прихожая, коридор' },
      trouble: { t: 'беда, неприятность' },
    },
  },

  {
    id: 'badly-on-purpose',
    title: 'Doing It Badly on Purpose',
    topic: 'разрешение делать плохо',
    genre: { id: 'motivation', label: 'Мотивация', emoji: '🌱' },
    imagePrompt: 'a table with a cheap sketchbook, a used pencil and a half-drunk cup of coffee',
    paragraphs: [
      '**Perfectionism does not look like high standards. It looks like an empty evening and a cupboard full of unopened boxes.** Rita had wanted to draw since she was nineteen. At thirty-four she owned good paper, three kinds of pencil, two books about technique and a folder of pictures by people whose work she loved. She had drawn eleven times in fifteen years, and each time she had stopped within an hour, because what appeared on the paper was not what was in her head.',
      'Her friend, who taught in a school and had heard every excuse a human being can produce, suggested something that sounded insulting: draw badly on purpose, for twenty minutes a day, for one month. Not "do your best". Not "relax and enjoy it". Deliberately, visibly badly, and keep every page.',
      'The first week was unpleasant in a way she had not expected. Doing something badly on purpose removes the comfortable excuse that you might have been good if only you had really tried. By the end of the second week the twenty minutes had stopped being a test of talent and had become simply a thing she did after dinner, like washing up.',
      'She is not an artist now; that is not the point of the story. But she draws four or five times a week, she can draw a hand from memory, and she has three pictures on her wall that she likes. What actually changed was small and technical: she stopped starting each attempt with the question "will this be good?", and the question had been the only thing that ever stopped her.',
      '**If something matters to you and you never do it, the problem is usually not laziness. It is that you have quietly agreed to only do it well — and nobody has ever done anything well the first forty times.**',
    ],
    questions: [
      {
        question: 'How often had Rita drawn in fifteen years?',
        options: ['Every week', 'Eleven times', 'Once a year', 'She had never drawn'],
        correctIndex: 1,
        explanation: 'За пятнадцать лет она рисовала одиннадцать раз.',
      },
      {
        question: 'What did her friend suggest?',
        options: [
          'To take a course',
          'To draw badly on purpose for twenty minutes a day',
          'To sell her materials',
          'To copy famous pictures',
        ],
        correctIndex: 1,
        explanation: 'Рисовать нарочно плохо по двадцать минут в день целый месяц.',
      },
      {
        question: 'Why was the first week unpleasant?',
        options: [
          'She had no time',
          'It removed the excuse that she could have been good if she had tried',
          'Her friend criticised her',
          'The paper was expensive',
        ],
        correctIndex: 1,
        explanation: 'Нарочно плохо — значит, больше нельзя утешаться, что «если бы постарался».',
      },
      {
        question: 'What actually changed for her?',
        options: [
          'She became a professional artist',
          'She stopped asking "will this be good?" before starting',
          'She bought better materials',
          'She started teaching drawing',
        ],
        correctIndex: 1,
        explanation: 'Она перестала начинать с вопроса «получится ли хорошо», а он и мешал.',
      },
    ],
    keyPoints: [
      'Рита хотела рисовать с девятнадцати лет и за пятнадцать лет села за это одиннадцать раз.',
      'У неё были бумага, карандаши и книги — не хватало только самого рисования.',
      'Подруга предложила рисовать нарочно плохо по двадцать минут в день месяц.',
      'Первая неделя далась тяжело: исчезло утешение «мог бы, если бы постарался».',
      'Она не стала художницей, но рисует регулярно и больше не спрашивает себя заранее, выйдет ли хорошо.',
    ],
    modelRetelling:
      'The text is about a woman who wanted to draw for many years but almost never did, because the result was never as good as the picture in her head. A friend told her to draw badly on purpose for twenty minutes every day for a month. The first week was hard, because she could no longer tell herself that she would be good if she really tried. After a month drawing became an ordinary evening habit, and she stopped asking whether the result would be good before starting.',
    discussion: [
      'Is there something you want to do but keep putting off?',
      'Do you recognise the feeling of wanting a result to be perfect immediately?',
      'What could you try to do badly on purpose this week?',
    ],
    glossary: {
      perfectionism: { t: 'перфекционизм' },
      standards: { t: 'стандарты, планка' },
      cupboard: { t: 'шкаф' },
      unopened: { t: 'нераспечатанный' },
      owned: { t: 'имела', l: 'own' },
      pencil: { t: 'карандаш' },
      technique: { t: 'техника' },
      folder: { t: 'папка' },
      appeared: { t: 'появлялось', l: 'appear' },
      excuse: { t: 'оправдание' },
      produce: { t: 'выдать, произвести' },
      suggested: { t: 'предложила', l: 'suggest' },
      insulting: { t: 'обидный' },
      purpose: { t: 'цель', n: 'on purpose — нарочно' },
      deliberately: { t: 'намеренно' },
      visibly: { t: 'заметно' },
      unpleasant: { t: 'неприятный' },
      removes: { t: 'убирает', l: 'remove' },
      comfortable: { t: 'удобный' },
      talent: { t: 'талант' },
      artist: { t: 'художник' },
      attempt: { t: 'попытка' },
      laziness: { t: 'лень' },
      quietly: { t: 'тихо, незаметно' },
      agreed: { t: 'согласились', l: 'agree' },
    },
  },
];
