/** Тексты 15–20. */
export default [
  {
    id: 'wrong-suitcase',
    title: 'The Wrong Suitcase',
    topic: 'чужой чемодан в аэропорту',
    genre: { id: 'thriller', label: 'Триллер', emoji: '⏱️' },
    imagePrompt: 'an airport baggage hall at night, one identical grey suitcase on an empty belt',
    paragraphs: [
      '**Every year thousands of people take the wrong bag from the belt, and every year almost all of them bring it back.** Marek noticed at the taxi rank that the wheels felt wrong. His suitcase was grey with a blue ribbon; this one was grey with a blue ribbon and about three kilos heavier. He stood on the pavement for a moment, tired after a night flight, and decided to sort it out at the hotel.',
      'The lock was the standard three-number kind and it was not locked. Inside there were clothes in his own size, a phone charger, and, under a folded jacket, a plastic box the size of a book. The box had no label and it was very cold. Marek closed the case again and sat on the bed with his hands on his knees, listening to somebody walking past in the corridor.',
      'The sensible thing was to call the airline, and he did. The woman on the line asked for the tag number, then went quiet for four seconds, and asked him to please stay where he was and not to open the suitcase. He did not tell her that he had opened it already. She asked for his room number twice, and he heard her typing both times.',
      'At half past two somebody knocked. Marek did not answer and did not move. The knocking stopped, and then his phone rang: an unknown number, the same three times. When he finally looked through the door hole, the corridor was empty and the light at the far end had been switched off, although it had been on when he arrived.',
      '**In the morning the case was gone from his room and his own suitcase stood in the corridor, undamaged, correctly labelled, with everything inside. He never learned what had been in the box, and he still, in airports, waits until the very last bag comes round.**',
    ],
    questions: [
      {
        question: 'How did Marek realise the suitcase was not his?',
        options: [
          'It was a different colour',
          'The wheels felt wrong and it was heavier',
          'The lock was broken',
          'A stranger told him',
        ],
        correctIndex: 1,
        explanation: 'На стоянке такси он почувствовал, что колёса катятся не так, и чемодан тяжелее.',
      },
      {
        question: 'What did he find inside?',
        options: [
          'Money',
          'Documents',
          'A cold plastic box with no label',
          'Nothing at all',
        ],
        correctIndex: 2,
        explanation: 'Под сложенной курткой лежала очень холодная коробка без надписей.',
      },
      {
        question: 'What was strange about the phone call to the airline?',
        options: [
          'The line was busy',
          'The woman asked him to stay and not open the case, and asked his room number twice',
          'They refused to help',
          'She said the case was empty',
        ],
        correctIndex: 1,
        explanation: 'Она замолчала на четыре секунды, попросила не открывать чемодан и дважды уточнила номер комнаты.',
      },
      {
        question: 'How does the story end?',
        options: [
          'The police arrest Marek',
          'The case disappears and his own is returned',
          'He opens the box',
          'He misses his flight home',
        ],
        correctIndex: 1,
        explanation: 'Утром чужой чемодан исчез, а его собственный стоял в коридоре целым.',
      },
    ],
    keyPoints: [
      'Марек забрал в аэропорту чужой чемодан, очень похожий на свой.',
      'Внутри под курткой лежала холодная коробка без надписей.',
      'В авиакомпании его попросили не открывать чемодан и дважды уточнили номер комнаты.',
      'Ночью кто-то стучал в дверь, звонил с неизвестного номера, а свет в коридоре погасили.',
      'Утром чужой чемодан пропал, его собственный вернули, и он так и не узнал, что было в коробке.',
    ],
    modelRetelling:
      'A man called Marek took the wrong suitcase at the airport, because it looked exactly like his own. In the hotel he opened it and found a cold plastic box without any label. He called the airline, and the woman asked him not to open the case and asked for his room number twice. At night somebody knocked at his door and called him from an unknown number. In the morning the suitcase had gone and his own one was standing in the corridor.',
    discussion: [
      'Have you ever lost a bag, or taken the wrong one?',
      'Would you have opened the suitcase, or called the airline first?',
      'What do you think was in the box?',
    ],
    glossary: {
      belt: { t: 'лента (багажная)' },
      rank: { t: 'стоянка', n: 'taxi rank — стоянка такси' },
      wheels: { t: 'колёса', l: 'wheel' },
      ribbon: { t: 'лента, ленточка' },
      kilos: { t: 'килограммы', l: 'kilo' },
      heavier: { t: 'тяжелее', l: 'heavy' },
      sort: { t: 'разобраться', n: 'sort it out — уладить' },
      standard: { t: 'обычный, стандартный' },
      charger: { t: 'зарядка' },
      folded: { t: 'сложенная', l: 'fold' },
      jacket: { t: 'куртка' },
      label: { t: 'надпись, ярлык' },
      knees: { t: 'колени', l: 'knee' },
      sensible: { t: 'разумный' },
      airline: { t: 'авиакомпания' },
      tag: { t: 'бирка' },
      typing: { t: 'печатала', l: 'type' },
      knocked: { t: 'постучал', l: 'knock' },
      unknown: { t: 'неизвестный' },
      hole: { t: 'глазок, отверстие' },
      undamaged: { t: 'целый, неповреждённый' },
      labelled: { t: 'с биркой', l: 'label' },
    },
  },

  {
    id: 'stopped-calling',
    title: 'The Friend You Stopped Calling',
    topic: 'дружба, которая тихо закончилась',
    genre: { id: 'motivation', label: 'Мотивация', emoji: '🌱' },
    imagePrompt: 'a phone on a table showing an unsent message, warm evening light in a kitchen',
    paragraphs: [
      '**Nobody ends a friendship. It simply stops being anybody\'s turn.** Sasha and Kolya were close for nine years and then, without a single argument, for four years they were not. There was no moment you could point at. There was a period when both of them were busy, and then a period when calling would have meant explaining the silence, and explaining the silence felt harder than staying quiet.',
      'This is how most friendships end: not in anger but in arithmetic. Every message costs a little effort, and the longer the gap, the higher the price of the next one. After a month you write "how are you". After a year you feel you owe a speech, and a speech needs an occasion, and there is never an occasion on an ordinary Wednesday. After three years the message you owe has become so large that no evening is ever the right evening to write it.',
      'The way out is smaller than people think. Sasha wrote eleven words: "I saw a red car like yours today and laughed." No apology, no summary of four years, no plan to meet. Kolya answered in nine minutes with a photograph of the same car, which he still had, and which was still breaking down.',
      'They did not become what they had been. Some things do not come back, and pretending otherwise is its own kind of lie. But they now speak every few weeks, and neither of them owes the other a speech any more, because the debt was never real. It was a story about how much a message has to weigh.',
      '**If somebody comes to mind while you are reading this, do not write the long message. Write the short one. The short one is the only one that ever actually gets sent.**',
    ],
    questions: [
      {
        question: 'Why did Sasha and Kolya stop talking?',
        options: [
          'They had a serious argument',
          'One of them moved abroad',
          'They got busy and the silence became hard to explain',
          'They worked together and it went wrong',
        ],
        correctIndex: 2,
        explanation: 'Ссоры не было: сначала оба были заняты, потом объяснять молчание стало тяжелее, чем молчать.',
      },
      {
        question: 'What does the writer mean by "arithmetic"?',
        options: [
          'They argued about money',
          'The longer the silence, the more effort the next message seems to need',
          'They counted their meetings',
          'Friendship depends on how often you meet',
        ],
        correctIndex: 1,
        explanation: 'Чем больше пауза, тем дороже кажется следующее сообщение.',
      },
      {
        question: 'What did Sasha finally write?',
        options: [
          'A long apology',
          'A short message about a red car',
          'An invitation to meet',
          'Nothing — Kolya wrote first',
        ],
        correctIndex: 1,
        explanation: 'Одиннадцать слов про красную машину, без извинений и планов.',
      },
      {
        question: 'What is the honest note in the ending?',
        options: [
          'Everything went back to normal',
          'They never spoke again',
          'They did not become what they had been, but they talk again',
          'Kolya was angry with him',
        ],
        correctIndex: 2,
        explanation: 'Автор прямо говорит: прежнего не вернуть, но общаются они снова.',
      },
    ],
    keyPoints: [
      'Саша и Коля дружили девять лет, а потом четыре года не общались — без ссоры.',
      'Дружбы чаще заканчиваются не от злости, а от «арифметики»: чем дольше пауза, тем дороже кажется следующий шаг.',
      'Через три года кажется, что нужно писать целую речь, и поэтому не пишешь ничего.',
      'Саша написал одиннадцать слов про красную машину, и Коля ответил через девять минут.',
      'Прежней дружбы не вернулось, но они снова общаются: долг был выдуманный.',
    ],
    modelRetelling:
      'The text is about two friends who stopped talking for four years without any argument. They were busy, and later it felt too difficult to explain the silence. The writer says that the longer you wait, the bigger the message seems to be. In the end one of them sent a very short message about a red car, and his friend answered in nine minutes. They are not as close as before, but they talk again.',
    discussion: [
      'Is there somebody you have not written to for a long time?',
      'Do you find it easy to start a conversation again after months of silence?',
      'What keeps a friendship alive when people live far apart?',
    ],
    glossary: {
      argument: { t: 'ссора, спор' },
      point: { t: 'указать', n: 'point at — указать на' },
      period: { t: 'период' },
      explaining: { t: 'объяснение', l: 'explain' },
      anger: { t: 'злость' },
      arithmetic: { t: 'арифметика' },
      effort: { t: 'усилие' },
      gap: { t: 'промежуток, пауза' },
      owe: { t: 'быть должным' },
      speech: { t: 'речь' },
      apology: { t: 'извинение' },
      summary: { t: 'краткое изложение' },
      breaking: { t: 'ломалась', l: 'break', n: 'break down — ломаться' },
      pretending: { t: 'притворяться', l: 'pretend' },
      otherwise: { t: 'иначе' },
      lie: { t: 'ложь' },
      debt: { t: 'долг' },
      weigh: { t: 'весить' },
      laughed: { t: 'засмеялся', l: 'laugh' },
      photograph: { t: 'фотография' },
      neither: { t: 'ни один из двух' },
    },
  },

  {
    id: 'time-faster',
    title: 'Why Time Feels Faster',
    topic: 'почему годы летят быстрее с возрастом',
    genre: { id: 'science', label: 'Научпоп', emoji: '🔬' },
    imagePrompt: 'a simple wall calendar with pages turning, soft light, minimal illustration',
    paragraphs: [
      '**Ask a child how long the summer is and they will tell you: enormous. Ask their father and he will say the summer was last week.** Almost everyone reports the same thing after thirty: the years arrive faster. This is not a feeling about clocks, which have not changed. It is a feeling about memory, and it has at least two explanations that are worth knowing.',
      'The first is simple mathematics. For a child of five, one year is twenty per cent of everything they have lived through. For a person of fifty it is two per cent. We seem to judge periods of time against the length of our whole life, so the same year is a much smaller piece of the picture each time it happens.',
      'The second explanation is stronger and more useful. Your sense of how long a period lasted comes largely from how many separate memories you can find in it. A first year in a new city is full of first times, so it leaves hundreds of markers, and later it feels long. A year of the same work, the same road home and the same evenings leaves almost nothing to count, and so it collapses to the size of a few weeks.',
      'This suggests something you can act on, which is rare in science writing. Novelty makes time feel longer afterwards. A different route home, a new skill in the evening, a weekend somewhere you have never been: each of these is a memory that will hold its own space. You cannot slow the clock, but you can give the year more to hold on to.',
      '**Time does not speed up as you get older. Your life simply stops giving your memory anything new to write down, and a year with nothing written in it reads very quickly.**',
    ],
    questions: [
      {
        question: 'What is the first explanation given in the text?',
        options: [
          'People sleep less as they get older',
          'A year is a smaller part of a longer life',
          'Clocks run differently',
          'Older people are busier',
        ],
        correctIndex: 1,
        explanation: 'Для пятилетнего год — 20% жизни, для пятидесятилетнего — 2%.',
      },
      {
        question: 'According to the second explanation, what makes a period feel long?',
        options: [
          'Many separate memories inside it',
          'Being tired at the end of it',
          'Working hard',
          'Counting the days',
        ],
        correctIndex: 0,
        explanation: 'Ощущение длины зависит от количества отдельных воспоминаний.',
      },
      {
        question: 'Why does a first year in a new city feel long?',
        options: [
          'It is usually difficult',
          'It is full of first times, so it leaves many markers',
          'People take more photographs',
          'The weather is different',
        ],
        correctIndex: 1,
        explanation: 'Много «первых раз» — много меток в памяти.',
      },
      {
        question: 'What practical advice does the writer give?',
        options: [
          'Sleep more',
          'Keep a diary every day',
          'Add new experiences, even small ones',
          'Work less',
        ],
        correctIndex: 2,
        explanation: 'Новизна — другой маршрут, новый навык, новое место — растягивает год задним числом.',
      },
    ],
    keyPoints: [
      'После тридцати почти все замечают, что годы идут быстрее.',
      'Первое объяснение — арифметика: год составляет всё меньшую долю прожитой жизни.',
      'Второе объяснение — память: длина периода зависит от числа отдельных воспоминаний в нём.',
      'Год из одинаковых дней почти не оставляет меток и «схлопывается».',
      'Практический вывод: новизна — новый маршрут, навык, поездка — растягивает время задним числом.',
    ],
    modelRetelling:
      'The text explains why time seems to go faster as we get older. The first reason is mathematical: one year is a smaller part of a long life than of a short one. The second reason is about memory: we judge how long a period was by how many different memories it contains. A year with new experiences feels long, and a year of routine feels short. So the writer suggests doing new things, because they give the memory something to keep.',
    discussion: [
      'Does time feel faster to you now than a few years ago?',
      'Which year of your life felt the longest, and why?',
      'What new thing could you try this month?',
    ],
    glossary: {
      enormous: { t: 'огромный' },
      reports: { t: 'сообщают', l: 'report' },
      clocks: { t: 'часы', l: 'clock' },
      explanations: { t: 'объяснения', l: 'explanation' },
      mathematics: { t: 'математика' },
      per: { t: 'за, на', n: 'per cent — процент' },
      cent: { t: 'процент', n: 'в составе per cent' },
      judge: { t: 'оценивать' },
      periods: { t: 'периоды', l: 'period' },
      whole: { t: 'целый' },
      piece: { t: 'кусок, часть' },
      sense: { t: 'ощущение' },
      lasted: { t: 'длился', l: 'last' },
      largely: { t: 'в основном' },
      separate: { t: 'отдельный' },
      markers: { t: 'метки', l: 'marker' },
      collapses: { t: 'схлопывается', l: 'collapse' },
      suggests: { t: 'подсказывает', l: 'suggest' },
      rare: { t: 'редкий' },
      novelty: { t: 'новизна' },
      afterwards: { t: 'потом, задним числом' },
      route: { t: 'маршрут' },
      skill: { t: 'навык' },
    },
  },

  {
    id: 'late-mirror',
    title: 'The Mirror Is Two Seconds Late',
    topic: 'зеркало, которое отстаёт',
    genre: { id: 'weird', label: 'Странное', emoji: '🌀' },
    imagePrompt: 'an old mirror in a hallway reflecting an empty room, dreamlike calm light',
    paragraphs: [
      '**The mirror in the hall had been in the flat longer than Ira had, and it was two seconds late.** She noticed it in October, brushing her hair: her hand stopped, and the hand in the glass finished the movement and only then stopped too. She watched for a while, tried it with her other hand, and then went to work, because it was Tuesday and she had a meeting at ten.',
      'Nobody else remarked on it. Her mother visited in November, stood in front of the mirror to put on her coat, and said only that Ira should eat more. A plumber came in December, worked in the bathroom for two hours, walked past the mirror eleven times and left without a word. The delay was clearly not a secret. It simply was not interesting to anyone but her.',
      'She began, without planning it, to use the mirror as a small companion. She would wave and then watch the wave arrive. On difficult evenings she would stand there and say something out loud, and two seconds later the woman in the glass would say it too, with exactly her face, and Ira found this steadying in a way she could not explain to anybody.',
      'In March the delay became four seconds, then a week later six. By April she had to wait, and waiting made her watch her own face while it was still, which is not a thing people usually do. She did not like what she saw, and then, slowly, she stopped minding it. In June the mirror caught up and was ordinary again.',
      '**Ira kept it, of course. Everyone has one thing in their home that stopped working and that they will never throw away, because for a while it was the only thing that waited for them.**',
    ],
    questions: [
      {
        question: 'What was unusual about the mirror?',
        options: [
          'It showed a different person',
          'The reflection was late',
          'It was always dark',
          'It made noises',
        ],
        correctIndex: 1,
        explanation: 'Отражение отставало: сначала на две секунды.',
      },
      {
        question: 'How did other people react to it?',
        options: [
          'They were frightened',
          'They did not comment at all',
          'They wanted to buy it',
          'They said it was broken',
        ],
        correctIndex: 1,
        explanation: 'Ни мать, ни сантехник ничего не сказали — задержка никого не интересовала.',
      },
      {
        question: 'What happened to the delay over time?',
        options: [
          'It disappeared at once',
          'It grew to six seconds and then went back to normal',
          'It stayed exactly two seconds',
          'It became a whole minute',
        ],
        correctIndex: 1,
        explanation: 'Задержка выросла до четырёх, потом до шести секунд, а в июне зеркало «догнало».',
      },
      {
        question: 'What is the story really about?',
        options: [
          'Repairing old things',
          'Being afraid of mirrors',
          'Loneliness and something that waits for you',
          'Moving to a new flat',
        ],
        correctIndex: 2,
        explanation: 'Финал: вещь, которая какое-то время была единственным, что тебя ждало.',
      },
    ],
    keyPoints: [
      'Зеркало в прихожей отставало на две секунды, и Ира заметила это в октябре.',
      'Остальные — мать, сантехник — вообще не обращали на это внимания.',
      'Ира стала пользоваться зеркалом как собеседником: махала рукой и ждала отражение.',
      'Задержка выросла до шести секунд, и ей пришлось подолгу смотреть на собственное неподвижное лицо.',
      'В июне зеркало догнало реальность, но Ира оставила его у себя.',
    ],
    modelRetelling:
      'The story is about a woman whose mirror shows the reflection two seconds later than it happens. Nobody else finds this strange or even mentions it. She starts using the mirror almost like a companion: she waves or speaks and then waits for the reflection to answer. The delay grows to six seconds and then disappears in June, and the mirror becomes ordinary again, but she keeps it because for a while it was the only thing that waited for her.',
    discussion: [
      'Do you have an old object at home that you will never throw away?',
      'Would the mirror frighten you, or would you get used to it?',
      'What do you think the delay means in the story?',
    ],
    glossary: {
      hall: { t: 'прихожая' },
      brushing: { t: 'расчёсывая', l: 'brush' },
      glass: { t: 'стекло; здесь — зеркало' },
      movement: { t: 'движение' },
      remarked: { t: 'заметил вслух', l: 'remark' },
      plumber: { t: 'сантехник' },
      delay: { t: 'задержка' },
      clearly: { t: 'явно' },
      secret: { t: 'секрет' },
      companion: { t: 'спутник, собеседник' },
      wave: { t: 'махать; взмах' },
      steadying: { t: 'успокаивающий', l: 'steady' },
      caught: { t: 'догнало', l: 'catch', n: 'catch up — догнать' },
      ordinary: { t: 'обычный' },
      minding: { t: 'возражать, обращать внимание', l: 'mind' },
      throw: { t: 'выбрасывать', n: 'throw away — выбросить' },
      waited: { t: 'ждало', l: 'wait' },
      reflection: { t: 'отражение' },
      still: { t: 'неподвижный' },
    },
  },

  {
    id: 'first-day',
    title: 'The First Day',
    topic: 'первый день на работе, которую не хотел',
    genre: { id: 'life', label: 'Из жизни', emoji: '☕' },
    imagePrompt: 'an open-plan office in the morning, one empty desk with a new keyboard, soft daylight',
    paragraphs: [
      '**He had taken the job for the money, and he told himself this in the lift, as if honesty made it better.** Anton was thirty-one. The previous six months had been a long lesson in how quickly savings become numbers you check at night. The company sold insurance software. His new manager met him at reception, said his name wrongly, and did not correct it for three weeks.',
      'The desk was fine. The chair was better than his chair at home. At eleven a woman from the next desk asked whether he wanted coffee, and he said no automatically, and then sat there for four minutes regretting it in a way that felt out of proportion. At lunch he ate alone in the kitchen and read the news twice without keeping any of it. Somebody had left a birthday card on the table for a person he had not met, and he signed it, because it seemed easier than explaining that he could not.',
      'What surprised him was three o\'clock. A colleague showed him how their oldest system worked, apologising for it, and Anton found himself asking a second question and then a third. The thing was badly built and interesting, like a house with rooms added by people who never met. For about forty minutes he forgot to feel sorry for himself.',
      'He went home tired in the ordinary way, not the frightened way. Nothing had been solved. He still did not want this job, and the job did not want anything from him except attendance. But he had learned that a day can be got through in pieces, and that inside a day you do not want there can be forty minutes that are simply work, and that those forty minutes are not nothing.',
      '**Most life changes do not begin with a decision. They begin with a Tuesday you survive slightly better than you expected to.**',
    ],
    questions: [
      {
        question: 'Why did Anton take the job?',
        options: ['He loved the field', 'For the money', 'A friend recommended it', 'It was near his home'],
        correctIndex: 1,
        explanation: 'Он взял работу ради денег и сам себе в этом признался в лифте.',
      },
      {
        question: 'What happened with the coffee?',
        options: [
          'He drank it with a colleague',
          'He said no automatically and then regretted it',
          'There was no coffee in the office',
          'He spilled it',
        ],
        correctIndex: 1,
        explanation: 'Он машинально отказался и потом четыре минуты об этом жалел.',
      },
      {
        question: 'What surprised him at three o\'clock?',
        options: [
          'He was given a pay rise',
          'The manager apologised',
          'He became genuinely interested in an old system',
          'He was allowed to go home early',
        ],
        correctIndex: 2,
        explanation: 'Старая система оказалась плохо устроенной, но интересной, и он забыл жалеть себя.',
      },
      {
        question: 'What is the main idea of the ending?',
        options: [
          'You should always follow your dream job',
          'Change often starts with a day you survive better than expected',
          'Money is the most important thing',
          'First days are always terrible',
        ],
        correctIndex: 1,
        explanation: 'Перемены начинаются не с решения, а со вторника, который прошёл чуть лучше ожидаемого.',
      },
    ],
    keyPoints: [
      'Антон в тридцать один год вышел на работу, которую взял только из-за денег.',
      'Полгода без работы научили его смотреть на сбережения как на тревожные цифры.',
      'Он машинально отказался от кофе и потом жалел об этом сильнее, чем стоило.',
      'В три часа коллега показал ему старую систему, и она неожиданно его увлекла.',
      'Ничего не решилось, но он понял: и в нежеланном дне бывают сорок нормальных минут.',
    ],
    modelRetelling:
      'The story describes the first day of a man who took a job only because he needed money. He felt uncomfortable: his manager said his name wrongly, he refused coffee without thinking and then regretted it, and he had lunch alone. In the afternoon a colleague showed him an old system in the company, and he asked questions and forgot to feel sorry for himself for forty minutes. Nothing was solved, but he went home tired in a normal way.',
    discussion: [
      'What do you remember about your first day at a job or school?',
      'Have you ever done work you did not enjoy? What made it easier?',
      'Do you agree that big changes start with small ordinary days?',
    ],
    glossary: {
      honesty: { t: 'честность' },
      previous: { t: 'предыдущий' },
      savings: { t: 'сбережения' },
      insurance: { t: 'страхование' },
      software: { t: 'программы, софт' },
      reception: { t: 'ресепшн, стойка' },
      wrongly: { t: 'неправильно' },
      correct: { t: 'исправить' },
      desk: { t: 'рабочий стол' },
      automatically: { t: 'машинально' },
      regretting: { t: 'сожалея', l: 'regret' },
      proportion: { t: 'соразмерность', n: 'out of proportion — несоразмерно' },
      colleague: { t: 'коллега' },
      apologising: { t: 'извиняясь', l: 'apologise' },
      badly: { t: 'плохо' },
      built: { t: 'построен', l: 'build' },
      solved: { t: 'решено', l: 'solve' },
      attendance: { t: 'присутствие' },
      pieces: { t: 'части', l: 'piece' },
      survive: { t: 'пережить' },
      slightly: { t: 'слегка' },
      expected: { t: 'ожидал', l: 'expect' },
    },
  },

  {
    id: 'house-complaint',
    title: 'The House Filed a Complaint',
    topic: 'дом, который пожаловался на хозяина',
    genre: { id: 'scifi', label: 'Фантастика', emoji: '🛰️' },
    imagePrompt: 'a calm modern living room at dusk with a small glowing panel by the door',
    paragraphs: [
      '**The letter was polite, correctly formatted, and signed by the building.** Under the new regulations a smart home could report conditions that shortened its own life: damp, overheating, structural damage. Vitaly had read about this in the news and found it funny. The letter said that flat 12 had been kept at eleven degrees for five months and that the north wall was now holding water.',
      'He was not cruel and he was not stupid. He was sixty-four and had calculated, correctly, that heating one room was cheaper than heating four, and that a coat indoors costs nothing. The house had no opinion about his pension, and this was the part he could not argue with. It had a temperature curve, a moisture reading, and a duty to report both, and none of those three things had ever been cold.',
      'The hearing took eleven minutes and was conducted by a woman who had clearly done forty of them that week. She did not fine him. She asked him three questions about his heating bills, wrote something, and told him that a fund existed for exactly this situation and that almost nobody applied to it, because almost nobody knew. Vitaly had lived in the flat for thirty-one years and had never heard of it either.',
      'The wall was repaired in the spring. He now keeps the flat at nineteen degrees and the house has reported nothing further. What he cannot decide, and what he thinks about while the new radiator ticks, is whether he was reported on or spoken for. Both are true, and they do not cancel each other out.',
      '**We built machines to watch the things we own. It turns out that a machine watching your house is also, whether anybody planned it or not, a machine watching how you live.**',
    ],
    questions: [
      {
        question: 'Who sent the letter to Vitaly?',
        options: ['His neighbour', 'The building itself', 'The city police', 'His daughter'],
        correctIndex: 1,
        explanation: 'Письмо было подписано зданием: умный дом обязан сообщать о вреде себе.',
      },
      {
        question: 'Why was the flat kept at eleven degrees?',
        options: [
          'The heating was broken',
          'He was saving money on heating',
          'He liked the cold',
          'He was away for months',
        ],
        correctIndex: 1,
        explanation: 'Виталию было дешевле топить одну комнату, а дома он ходил в куртке.',
      },
      {
        question: 'What did the woman at the hearing do?',
        options: [
          'She fined him heavily',
          'She told him about a fund almost nobody knew about',
          'She sent him to another office',
          'She switched off his heating',
        ],
        correctIndex: 1,
        explanation: 'Штрафа не было: она рассказала о фонде помощи, о котором почти никто не знает.',
      },
      {
        question: 'What does Vitaly think about afterwards?',
        options: [
          'Whether to move house',
          'Whether he was reported on or spoken for',
          'How to switch the system off',
          'Whether the wall will break again',
        ],
        correctIndex: 1,
        explanation: 'Он не может решить, донесли на него или заступились — и верно и то, и другое.',
      },
    ],
    keyPoints: [
      'По новым правилам умный дом может сообщать о том, что сокращает срок его службы.',
      'Дом пожаловался, что квартиру пять месяцев держат при одиннадцати градусах и стена намокла.',
      'Виталий экономил на отоплении: топить одну комнату дешевле, чем четыре.',
      'На разбирательстве его не оштрафовали, а рассказали о фонде помощи, о котором он не знал.',
      'Стену починили, но он так и не решил, донесли на него или за него заступились.',
    ],
    modelRetelling:
      'In this story a smart building can send official reports about anything that damages it. An older man receives a letter from his own house, because he kept the flat at eleven degrees to save money and the wall became wet. At the hearing he is not fined; instead the official tells him about a fund that helps people pay for heating, which he had never heard of. The wall is repaired, and he keeps thinking about whether the house reported him or helped him.',
    discussion: [
      'Would you like your home to send reports about how you live in it?',
      'Where is the line between useful technology and too much watching?',
      'Has a machine or an app ever told you something useful about yourself?',
    ],
    glossary: {
      filed: { t: 'подал', l: 'file', n: 'file a complaint — подать жалобу' },
      complaint: { t: 'жалоба' },
      formatted: { t: 'оформленный', l: 'format' },
      signed: { t: 'подписан', l: 'sign' },
      regulations: { t: 'правила, регламент' },
      conditions: { t: 'условия', l: 'condition' },
      shortened: { t: 'сокращали', l: 'shorten' },
      damp: { t: 'сырость' },
      overheating: { t: 'перегрев' },
      structural: { t: 'конструктивный' },
      degrees: { t: 'градусы', l: 'degree' },
      cruel: { t: 'жестокий' },
      calculated: { t: 'подсчитал', l: 'calculate' },
      pension: { t: 'пенсия' },
      curve: { t: 'кривая, график' },
      moisture: { t: 'влажность' },
      duty: { t: 'обязанность' },
      hearing: { t: 'слушание' },
      conducted: { t: 'вела', l: 'conduct' },
      fine: { t: 'штрафовать; штраф' },
      bills: { t: 'счета', l: 'bill' },
      fund: { t: 'фонд' },
      applied: { t: 'обращался', l: 'apply' },
      repaired: { t: 'починена', l: 'repair' },
      radiator: { t: 'батарея' },
      ticks: { t: 'потрескивает', l: 'tick' },
      cancel: { t: 'отменять' },
    },
  },
];
