/** Тексты 10–14. */
export default [
  {
    id: 'dog-not-bark',
    title: 'The Dog That Did Not Bark',
    topic: 'кража на тихой улице',
    genre: { id: 'mystery', label: 'Детектив', emoji: '🔎' },
    imagePrompt: 'a dark suburban garden at night with an open gate and a sleeping dog',
    paragraphs: [
      '**A good witness tells you what happened. A great one tells you what did not.** The Petrov family came home from the coast on Sunday evening and found the back door open and the safe empty. Nothing else was touched: the television, the computer, even a envelope of cash in the kitchen drawer were exactly where they had left them.',
      'The street was quiet and everyone knew everyone. Mrs Egorova, who lived opposite and slept badly, said she had heard nothing unusual. The Petrovs had a large old dog called Bes, who barked at cats, at the postman, and once, memorably, at a plastic bag for eleven minutes. On Saturday night, said Mrs Egorova, Bes did not make a sound. She remembered this clearly, because the silence was what had let her sleep until six.',
      'Inspector Larin listened to this twice. Then he asked her a question that seemed to be about nothing: how many people did the dog know well? Four, she said. The parents, the daughter, and the daughter\'s young man, who came at weekends and always brought the dog a piece of sausage. Bes met him at the gate now, she added, in the way dogs meet people who belong to the house.',
      'The safe had not been broken. It had been opened, closed again, and left looking untouched, which is what a person does when they are not in a hurry and expect to come back to this house. The thief had known the code, known the family were away, and known the dog — or rather, the dog had known the thief. Everything valuable that was left behind had been left on purpose, so that the loss would look small and ordinary.',
      '**Larin thanked Mrs Egorova and asked for the young man\'s address. Silence is not the absence of evidence. Sometimes silence is the evidence.**',
    ],
    questions: [
      {
        question: 'What was taken from the house?',
        options: ['The television', 'Money from the safe', 'A computer', 'Nothing at all'],
        correctIndex: 1,
        explanation: 'Сейф оказался пуст, при этом телевизор, компьютер и деньги в ящике не тронули.',
      },
      {
        question: 'Why is the dog important?',
        options: [
          'It was stolen too',
          'It barked all night',
          'It did not bark, although it barks at everything',
          'It ran away',
        ],
        correctIndex: 2,
        explanation: 'Пёс лает на всё подряд, но в ту ночь молчал — значит, знал пришедшего.',
      },
      {
        question: 'What does the state of the safe suggest?',
        options: [
          'The thief was in a hurry',
          'The thief knew the code and planned to return',
          'The safe was already broken',
          'The family forgot to lock it',
        ],
        correctIndex: 1,
        explanation: 'Сейф не взломали, а открыли и аккуратно закрыли — так делает свой человек.',
      },
      {
        question: 'Who does the inspector suspect?',
        options: ['Mrs Egorova', 'The postman', 'The daughter\'s boyfriend', 'A stranger from another town'],
        correctIndex: 2,
        explanation: 'Он просит адрес молодого человека, который приезжал по выходным и кормил собаку.',
      },
    ],
    keyPoints: [
      'Семья Петровых вернулась с моря и обнаружила открытую заднюю дверь и пустой сейф.',
      'Больше ничего не взяли, хотя деньги и техника лежали на виду.',
      'Соседка сказала, что старый пёс, который лает на всё, в ту ночь молчал.',
      'Сейф не взломали, а аккуратно открыли и закрыли — значит, знали код.',
      'Инспектор попросил адрес жениха дочери, которого пёс хорошо знал.',
    ],
    modelRetelling:
      'A family came home and found that money had been taken from their safe, but nothing else was touched. A neighbour said she had heard nothing, and the family dog, which barks at everything, was silent that night. The safe was not broken, only opened and closed again. The inspector understood that the thief knew the code and was known to the dog, so he asked for the address of the daughter\'s boyfriend.',
    discussion: [
      'Do you enjoy stories where a small detail solves everything?',
      'Have you ever guessed something because of what somebody did not say?',
      'Do you think the boyfriend is guilty? What else could explain the silence?',
    ],
    glossary: {
      witness: { t: 'свидетель' },
      coast: { t: 'побережье' },
      safe: { t: 'сейф', n: 'здесь существительное, не «безопасный»' },
      touched: { t: 'тронут', l: 'touch' },
      envelope: { t: 'конверт' },
      cash: { t: 'наличные' },
      drawer: { t: 'ящик' },
      opposite: { t: 'напротив' },
      unusual: { t: 'необычный' },
      barked: { t: 'лаял', l: 'bark' },
      postman: { t: 'почтальон' },
      memorably: { t: 'запоминающе' },
      plastic: { t: 'пластиковый' },
      inspector: { t: 'инспектор' },
      sausage: { t: 'колбаса' },
      untouched: { t: 'нетронутый' },
      thief: { t: 'вор' },
      code: { t: 'код' },
      rather: { t: 'вернее' },
      absence: { t: 'отсутствие' },
      evidence: { t: 'улика, доказательство' },
      silence: { t: 'тишина, молчание' },
    },
  },

  {
    id: 'trees-talk',
    title: 'How Trees Warn Each Other',
    topic: 'как деревья предупреждают соседей',
    genre: { id: 'science', label: 'Научпоп', emoji: '🔬' },
    imagePrompt: 'sunlight through a forest, roots and soil visible, clean scientific illustration style',
    paragraphs: [
      '**A tree cannot run away, cannot hide and cannot call for help. So it does something stranger: it sends a message.** In the 1980s scientists in Africa noticed that antelopes eating from one acacia tree soon stopped and moved on, sometimes walking past several trees before eating again. The leaves they left behind had become bitter and hard to digest, and so had the leaves of nearby trees that nothing had touched.',
      'The explanation turned out to be chemical. A damaged leaf releases gas into the air, and neighbouring trees react to that gas by changing the chemistry of their own leaves within minutes. It is not conversation in any human sense. It is closer to smoke from a fire: the first tree is not trying to help anyone, but the signal is there, and the others use it.',
      'Under the ground there is a second system, and it is even less like a plant and more like a network. Thin threads of fungus grow between roots and connect trees of different ages and even different species. Sugar, water and warning signals travel along these threads. Older trees with more light often pass sugar to small trees standing in shadow, including trees that are not related to them at all.',
      'It is easy to make this too romantic. Nobody has shown that a forest is kind, and much of this exchange also benefits the fungus, which takes its own payment in sugar. But something in the old picture has to change. A forest is not a collection of trees standing next to each other, in the way that a crowd is not simply many separate people.',
      '**We used to ask which tree grows fastest. The better question turned out to be a different one: what is a tree connected to?**',
    ],
    questions: [
      {
        question: 'What did scientists notice about antelopes and acacia trees?',
        options: [
          'The antelopes ate more each year',
          'The antelopes stopped eating and walked past several trees',
          'The trees died quickly',
          'The antelopes avoided the forest',
        ],
        correctIndex: 1,
        explanation: 'Антилопы переставали есть и проходили мимо нескольких деревьев.',
      },
      {
        question: 'How does a damaged tree warn its neighbours above ground?',
        options: [
          'By dropping its leaves',
          'By moving its branches',
          'By releasing a gas into the air',
          'By changing colour',
        ],
        correctIndex: 2,
        explanation: 'Повреждённый лист выпускает газ, и соседние деревья меняют химию своих листьев.',
      },
      {
        question: 'What connects trees under the ground?',
        options: ['Thin threads of fungus', 'Small animals', 'Water pipes', 'Their own roots only'],
        correctIndex: 0,
        explanation: 'Тонкие нити грибницы соединяют корни деревьев разного возраста и вида.',
      },
      {
        question: 'What warning does the writer give?',
        options: [
          'The research is completely wrong',
          'It is easy to make this sound too romantic',
          'Forests are dangerous places',
          'Trees are more intelligent than animals',
        ],
        correctIndex: 1,
        explanation: 'Никто не доказал, что лес «добрый»: грибница берёт свою плату сахаром.',
      },
    ],
    keyPoints: [
      'В 1980-х заметили, что антилопы, поев с акации, уходят и обходят соседние деревья.',
      'Повреждённый лист выпускает газ, и соседи заранее меняют химию своих листьев.',
      'Под землёй деревья соединены нитями грибницы, по которым идут сахар, вода и сигналы.',
      'Старые деревья нередко передают сахар молодым, даже неродственным.',
      'Автор предостерегает от романтики: грибница получает свою выгоду, но лес — не просто набор отдельных деревьев.',
    ],
    modelRetelling:
      'The text explains how trees warn each other. Scientists saw that antelopes stopped eating acacia leaves, because a damaged tree releases a gas and nearby trees make their leaves bitter. Under the ground, thin threads of fungus connect the roots of different trees, and sugar, water and signals travel along them. Older trees often give sugar to small trees in the shadow. The writer says we should not make this too romantic, because the fungus also gets something for itself.',
    discussion: [
      'Did anything in this text surprise you?',
      'Do you spend much time in forests or parks? How do they make you feel?',
      'Should we protect old trees more than young ones? Why?',
    ],
    glossary: {
      warn: { t: 'предупреждать' },
      hide: { t: 'прятаться' },
      scientists: { t: 'учёные', l: 'scientist' },
      antelopes: { t: 'антилопы', l: 'antelope' },
      acacia: { t: 'акация' },
      leaves: { t: 'листья', l: 'leaf' },
      bitter: { t: 'горький' },
      digest: { t: 'переваривать' },
      nearby: { t: 'соседний' },
      explanation: { t: 'объяснение' },
      chemical: { t: 'химический' },
      damaged: { t: 'повреждённый', l: 'damage' },
      releases: { t: 'выпускает', l: 'release' },
      gas: { t: 'газ' },
      neighbouring: { t: 'соседние' },
      chemistry: { t: 'химия, химический состав' },
      signal: { t: 'сигнал' },
      threads: { t: 'нити', l: 'thread' },
      fungus: { t: 'грибница, гриб' },
      roots: { t: 'корни', l: 'root' },
      species: { t: 'вид (биологический)' },
      sugar: { t: 'сахар' },
      shadow: { t: 'тень' },
      related: { t: 'родственный' },
      romantic: { t: 'романтичный' },
      exchange: { t: 'обмен' },
      benefits: { t: 'приносит пользу', l: 'benefit' },
      payment: { t: 'плата' },
      collection: { t: 'набор, собрание' },
      crowd: { t: 'толпа' },
      separate: { t: 'отдельный' },
      connected: { t: 'связан', l: 'connect' },
    },
  },

  {
    id: 'last-dinner',
    title: 'The Last Dinner',
    topic: 'ужин перед отъездом друга',
    genre: { id: 'life', label: 'Из жизни', emoji: '☕' },
    imagePrompt: 'a small kitchen table with three plates, warm lamp light, an open suitcase in the corner',
    paragraphs: [
      '**Nobody in the kitchen said the word "last", and everybody was thinking it.** Pavel was flying on Thursday, and this was Tuesday, and Olga had cooked the thing she always cooked when she did not know what to say: too much food. Three of them sat around a table made for six. The suitcase stood in the corner of the room like a fourth guest, already dressed to leave.',
      'They talked about the flight, then about the price of flats in Lisbon, then about a film none of them had actually finished. Somebody made a joke about the weather there, and it was not funny, and everybody laughed anyway. Between the jokes there were small silences, and in every silence the same sentence stood up and sat down again without being said: it will not be like this any more.',
      'At half past eleven Pavel started saying that he should go, and stayed for forty minutes. He looked at the shelf near the door, where a photograph from a trip nine years ago had been standing in the same place since they moved in. Nobody had chosen that photograph. It had simply stayed, the way most important things do.',
      'When he finally left, Olga washed the plates although the machine was empty, and her husband dried them, although they always left them to dry by themselves. They were both being careful with each other, and both understood why, and neither of them mentioned it. It was almost one in the morning when she said, to the window rather than to him, that she was glad Pavel had come.',
      '**Goodbyes are rarely dramatic. Usually they look like an ordinary evening in which everybody is slightly too polite, and only later, when you remember it, does the evening become something else.**',
    ],
    questions: [
      {
        question: 'Why did Olga cook so much food?',
        options: [
          'Many guests were expected',
          'It was a holiday',
          'She did not know what to say',
          'Pavel had asked her to',
        ],
        correctIndex: 2,
        explanation: 'Она всегда готовила слишком много, когда не знала, что сказать.',
      },
      {
        question: 'What did the suitcase in the corner represent?',
        options: [
          'A gift for Pavel',
          'The coming departure, like a fourth guest',
          'Olga\'s work things',
          'Rubbish to throw away',
        ],
        correctIndex: 1,
        explanation: 'Чемодан стоял как четвёртый гость, уже одетый на выход.',
      },
      {
        question: 'How did Olga and her husband behave after Pavel left?',
        options: [
          'They argued',
          'They went straight to bed',
          'They did small unnecessary things carefully',
          'They called Pavel again',
        ],
        correctIndex: 2,
        explanation: 'Она мыла тарелки, хотя машина была пустой, он их вытирал, хотя обычно так не делали.',
      },
      {
        question: 'What is the main idea of the last paragraph?',
        options: [
          'Goodbyes are usually quiet and become meaningful later',
          'People should say goodbye properly',
          'Friends always come back',
          'Dinners are the best way to say goodbye',
        ],
        correctIndex: 0,
        explanation: 'Прощания редко бывают драматичными: обычный вечер, который позже станет чем-то другим.',
      },
    ],
    keyPoints: [
      'Павел улетал в четверг, и во вторник друзья собрались на ужин.',
      'Ольга наготовила слишком много еды, потому что не знала, что сказать.',
      'Разговор был обычный — рейс, цены, фильм — и в паузах висело невысказанное.',
      'Павел долго не мог уйти и разглядывал старую фотографию у двери.',
      'После его ухода супруги мыли и вытирали посуду, хотя обычно так не делали.',
    ],
    modelRetelling:
      'The story describes a dinner two days before a friend called Pavel moves abroad. Nobody says that it is the last dinner, but everybody feels it. They talk about ordinary things and laugh at jokes that are not funny. Pavel says he should go and then stays for another forty minutes. After he leaves, the couple wash and dry the plates carefully, without talking about how they feel. The writer says that goodbyes usually look like ordinary evenings.',
    discussion: [
      'Has a close friend of yours moved to another city or country?',
      'Do you find it easy to say goodbye, or do you avoid the moment?',
      'What ordinary evening from your past became important only later?',
    ],
    glossary: {
      suitcase: { t: 'чемодан' },
      guest: { t: 'гость' },
      flight: { t: 'рейс, полёт' },
      flats: { t: 'квартиры', l: 'flat' },
      joke: { t: 'шутка' },
      anyway: { t: 'всё равно' },
      silences: { t: 'паузы', l: 'silence' },
      sentence: { t: 'фраза, предложение' },
      shelf: { t: 'полка' },
      photograph: { t: 'фотография' },
      trip: { t: 'поездка' },
      chosen: { t: 'выбрал', l: 'choose' },
      simply: { t: 'просто' },
      washed: { t: 'мыла', l: 'wash' },
      plates: { t: 'тарелки', l: 'plate' },
      although: { t: 'хотя' },
      dried: { t: 'вытирал', l: 'dry' },
      careful: { t: 'осторожный, бережный' },
      neither: { t: 'ни тот ни другой' },
      mentioned: { t: 'упомянул', l: 'mention' },
      glad: { t: 'рад' },
      goodbyes: { t: 'прощания', l: 'goodbye' },
      rarely: { t: 'редко' },
      dramatic: { t: 'драматичный' },
      slightly: { t: 'слегка' },
      polite: { t: 'вежливый' },
    },
  },

  {
    id: 'last-translator',
    title: 'The Last Human Translator',
    topic: 'работа, которую почти отдали машинам',
    genre: { id: 'scifi', label: 'Фантастика', emoji: '🛰️' },
    imagePrompt: 'a quiet office with one desk, an old paper dictionary, and a glowing screen at night',
    paragraphs: [
      '**By 2041 the machines translated everything, and they were better than people at almost all of it.** Contracts, manuals, medicine, films, the news: all instant, all free, all correct. Anna still had a job, which surprised everybody at parties, including Anna. She worked for a court, and her work was the small percentage that the machines got right in every way except one.',
      'The case that year involved a family from a mountain village and a company that had built a road through their land. The company\'s translation of the villagers\' statement was accurate. Every word matched. But in that language there were two ways of saying "we agreed", and the difference between them was the difference between "we said yes" and "we stopped saying no".',
      'The machine chose the first. It had eleven million examples, and in almost all of them the two forms meant the same thing. Anna had lived in that region for two years when she was twenty-four, and she knew that villagers used the second form when a decision had been made by somebody else and they were being polite about it.',
      'She wrote a note of four lines and attached it to the file, which took her nine minutes and cost the company most of what it had already won. The judge read the note, then read the statement again, then asked the company a question that had not been asked in fourteen months of hearings. The case took another year, and the family kept a part of their land, and nobody outside the court ever heard about the two forms of one word.',
      '**Machines learn from what most people usually mean. Somebody still has to notice the moment when a person means something else, and that moment is where the whole case lives.**',
    ],
    questions: [
      {
        question: 'Why did Anna still have a job in 2041?',
        options: [
          'Machines could not translate contracts',
          'She worked on the rare cases where accuracy is not enough',
          'She was cheaper than machines',
          'The court did not trust technology',
        ],
        correctIndex: 1,
        explanation: 'Машины переводили точно, но она занималась теми случаями, где точности мало.',
      },
      {
        question: 'What was the problem with the villagers\' statement?',
        options: [
          'It was written badly',
          'Two forms of "we agreed" mean different things',
          'It was too long',
          'The machine could not read it',
        ],
        correctIndex: 1,
        explanation: '«Мы сказали да» и «мы перестали говорить нет» — разные вещи.',
      },
      {
        question: 'How did Anna know the difference?',
        options: [
          'She read about it',
          'The villagers told her',
          'She had lived in that region for two years',
          'The machine suggested it',
        ],
        correctIndex: 2,
        explanation: 'В двадцать четыре года она два года прожила в том регионе.',
      },
      {
        question: 'What is the main idea of the story?',
        options: [
          'Machines are dangerous',
          'Courts work too slowly',
          'Somebody has to notice when a person means something unusual',
          'Old jobs never disappear',
        ],
        correctIndex: 2,
        explanation: 'Машина учится на том, что обычно имеют в виду; человек ловит исключение.',
      },
    ],
    keyPoints: [
      'К 2041 году машины переводят почти всё лучше людей, но Анна работает переводчицей в суде.',
      'В деле о дороге через землю деревни перевод машины был формально точным.',
      'В том языке два способа сказать «мы согласились»: «мы сказали да» и «мы перестали говорить нет».',
      'Анна знала разницу, потому что два года жила в том регионе.',
      'Её записка на четыре строки изменила ход дела, и семья сохранила часть земли.',
    ],
    modelRetelling:
      'In this story machines do almost all translation in 2041, but a woman called Anna still works for a court. In one case a company translated a statement from a mountain village correctly, word by word. However, that language has two ways of saying "we agreed", and one of them really means "we stopped saying no". Anna knew this because she had lived there, so she wrote a note to the judge, and the family kept part of their land.',
    discussion: [
      'Which jobs do you think machines will not take soon?',
      'Have you ever used a translation app and got a strange result?',
      'Is it important to learn a language when translation is instant and free?',
    ],
    glossary: {
      translated: { t: 'переводили', l: 'translate' },
      contracts: { t: 'договоры', l: 'contract' },
      manuals: { t: 'инструкции', l: 'manual' },
      medicine: { t: 'медицина' },
      instant: { t: 'мгновенный' },
      surprised: { t: 'удивляло', l: 'surprise' },
      court: { t: 'суд' },
      percentage: { t: 'процент, доля' },
      involved: { t: 'касалось', l: 'involve' },
      village: { t: 'деревня' },
      villagers: { t: 'жители деревни' },
      statement: { t: 'заявление, показания' },
      accurate: { t: 'точный' },
      matched: { t: 'совпадало', l: 'match' },
      forms: { t: 'формы', l: 'form' },
      examples: { t: 'примеры', l: 'example' },
      region: { t: 'регион' },
      decision: { t: 'решение' },
      polite: { t: 'вежливый' },
      attached: { t: 'приложила', l: 'attach' },
      judge: { t: 'судья' },
      hearings: { t: 'слушания', l: 'hearing' },
      notice: { t: 'заметить' },
    },
  },

  {
    id: 'baby-monitor',
    title: 'The Voice on the Monitor',
    topic: 'детская радионяня по ночам',
    genre: { id: 'horror', label: 'Ужастик', emoji: '🕯️' },
    imagePrompt: 'a dark nursery seen through a baby monitor screen, green light, empty cot',
    paragraphs: [
      '**For eight weeks the monitor worked perfectly, and that is why nobody questioned it on the ninth.** Nadia and Tim had bought the cheapest model with a screen: a small green picture of the cot, a light that showed sound, and a battery that lasted until morning. Their daughter was six months old and slept badly, so the monitor stayed on the pillow between them all night.',
      'On Wednesday, at about two, Nadia woke to the sound of somebody singing. It was quiet and slow, a song without real words, the kind you make up when you are too tired to remember a proper one. She listened for a while with her eyes closed. Then she understood two things at the same time: it was a woman\'s voice, and Tim was asleep beside her, breathing slowly against her shoulder.',
      'She was in the other room in five seconds. Her daughter was awake, lying on her back, calm, looking up and to the left, at the corner above the wardrobe where there was nothing but paint. The singing had stopped the moment Nadia opened the door. The room was cold, and the window, which she had closed herself at nine, was open two centimetres.',
      'They changed the monitor the next day, then the room, and finally the flat. Nadia told the story twice: once to her sister, who suggested a neighbour\'s radio, and once to a doctor, who suggested tiredness. Both explanations were sensible, and she agreed with them out loud, and she never slept in that flat again. Tim believed the radio, or said he did, which in a marriage is often the same thing.',
      '**Her daughter is eleven now and remembers nothing. But she still, in a certain kind of silence, looks up and to the left — and Nadia has never once asked her why.**',
    ],
    questions: [
      {
        question: 'Why did the family keep the monitor on all night?',
        options: [
          'It was broken',
          'Their daughter slept badly',
          'They liked the green light',
          'The battery needed charging',
        ],
        correctIndex: 1,
        explanation: 'Дочь плохо спала, поэтому радионяня лежала на подушке между родителями.',
      },
      {
        question: 'What made the singing frightening?',
        options: [
          'It was very loud',
          'It was a woman\'s voice while Tim was asleep next to her',
          'It came from the street',
          'It repeated the same word',
        ],
        correctIndex: 1,
        explanation: 'Голос был женский, а Тим спал рядом — значит, пел кто-то ещё.',
      },
      {
        question: 'What did Nadia find in the room?',
        options: [
          'Her daughter crying',
          'A stranger by the window',
          'Her daughter calm, looking at an empty corner',
          'The monitor switched off',
        ],
        correctIndex: 2,
        explanation: 'Дочь лежала спокойно и смотрела вверх и влево, в пустой угол над шкафом.',
      },
      {
        question: 'Why is the last paragraph unsettling?',
        options: [
          'The daughter still looks at that corner',
          'The family moved again',
          'The monitor was never found',
          'The mother forgot everything',
        ],
        correctIndex: 0,
        explanation: 'Дочь ничего не помнит, но в тишине смотрит туда же — и мать никогда не спрашивает почему.',
      },
    ],
    keyPoints: [
      'Восемь недель радионяня работала нормально, поэтому на девятую никто ничего не заподозрил.',
      'Ночью Надя проснулась от тихого женского пения в мониторе, а муж спал рядом.',
      'В детской дочь лежала спокойно и смотрела в пустой угол, пение прекратилось.',
      'Окно, закрытое вечером, оказалось приоткрыто, и в комнате было холодно.',
      'Семья сменила монитор, комнату и квартиру; дочь ничего не помнит, но до сих пор смотрит в ту же сторону.',
    ],
    modelRetelling:
      'A young family used a cheap baby monitor because their daughter slept badly. One night the mother heard a woman singing through it, but her husband was asleep next to her. She ran to the child\'s room and found her daughter awake and calm, looking at an empty corner, and the singing stopped. The window she had closed was open a little and the room was cold. The family moved away, and the daughter still looks at that same corner today.',
    discussion: [
      'Do you believe stories like this, or do you look for a normal explanation?',
      'What is the most frightening thing you have heard at night?',
      'Why do you think small children often look at empty corners?',
    ],
    glossary: {
      monitor: { t: 'радионяня, монитор' },
      questioned: { t: 'сомневался', l: 'question' },
      cheapest: { t: 'самый дешёвый', l: 'cheap' },
      screen: { t: 'экран' },
      cot: { t: 'детская кроватка' },
      battery: { t: 'батарея' },
      lasted: { t: 'хватало', l: 'last' },
      daughter: { t: 'дочь' },
      pillow: { t: 'подушка' },
      singing: { t: 'пение', l: 'sing' },
      proper: { t: 'настоящий, подходящий' },
      asleep: { t: 'спящий' },
      breathing: { t: 'дышал', l: 'breathe' },
      shoulder: { t: 'плечо' },
      awake: { t: 'бодрствующий' },
      calm: { t: 'спокойный' },
      corner: { t: 'угол' },
      wardrobe: { t: 'шкаф' },
      paint: { t: 'краска' },
      centimetres: { t: 'сантиметры' },
      suggested: { t: 'предположила', l: 'suggest' },
      tiredness: { t: 'усталость' },
      sensible: { t: 'разумный' },
      certain: { t: 'определённый' },
    },
  },
];
