/** Тексты 6–9. */
export default [
  {
    id: 'eight-minutes',
    title: 'Eight Minutes',
    topic: 'чужой кабинет и время на часах',
    genre: { id: 'thriller', label: 'Триллер', emoji: '⏱️' },
    imagePrompt: 'an empty office at night lit by one desk lamp, an open drawer, tense mood',
    paragraphs: [
      '**The cleaner left at 21:40. Dmitri had eight minutes before the security guard walked the fourth floor.** He had counted the route three times that week, holding a cup of coffee, looking bored. Left from the lift, past the meeting room, second door on the right. The lock was old. The file was in the second drawer, and after tonight nobody would be able to say that the accident had been his fault.',
      'The office smelled of paper and cold tea. He found the drawer at once, and the folder was exactly where his colleague had described it, under a box of pens. Dmitri put it on the desk and took out his phone to photograph the pages. Twelve pages. Thirty seconds each, if his hands stayed steady. They did not stay steady.',
      'At page seven he heard the lift. It was too early — far too early — and it stopped on his floor. Dmitri turned off the lamp and stood behind the door in the dark, listening to shoes on the hard floor, coming closer, then stopping. A key moved in a lock, but it was the wrong lock, the room next door. Somebody coughed. A chair moved. Then silence, and the small sound of a computer starting up.',
      'He waited. Two minutes, three. His shirt was wet against his back. When he finally understood that the person was not leaving, he did the only thing left: he picked up the folder, walked out with it in his hand, and passed the open door of the next room without turning his head.',
      '**In the lift he looked at his phone. Seven photographs, five pages missing, and a folder in his hand that somebody would notice by Monday. He had planned every second of those eight minutes, and no part of the plan told him what to do with the ninth.**',
    ],
    questions: [
      {
        question: 'Why did Dmitri come to the office at night?',
        options: [
          'To finish his own work',
          'To photograph pages from a file',
          'To meet a colleague',
          'To repair a lock',
        ],
        correctIndex: 1,
        explanation: 'Он пришёл сфотографировать двенадцать страниц из папки.',
      },
      {
        question: 'What went wrong with his plan?',
        options: [
          'The drawer was locked',
          'The file was not there',
          'Somebody arrived earlier than expected',
          'His phone stopped working',
        ],
        correctIndex: 2,
        explanation: 'Лифт приехал слишком рано, и человек зашёл в соседний кабинет.',
      },
      {
        question: 'What did Dmitri finally do?',
        options: [
          'He hid under the desk',
          'He put the folder back',
          'He took the folder with him',
          'He called security',
        ],
        correctIndex: 2,
        explanation: 'Он взял папку и вышел с ней в руке.',
      },
      {
        question: 'Why is the ending tense?',
        options: [
          'He lost his phone',
          'The missing folder will be noticed and he has only part of the pages',
          'The lift stopped working',
          'He forgot the way out',
        ],
        correctIndex: 1,
        explanation: 'Семь фото из двенадцати, а пропажу папки заметят к понедельнику.',
      },
    ],
    keyPoints: [
      'Дмитрий пробрался в чужой кабинет между уходом уборщицы и обходом охраны — у него было восемь минут.',
      'Он нашёл папку и начал фотографировать двенадцать страниц.',
      'На седьмой странице приехал лифт, и кто-то зашёл в соседний кабинет.',
      'Человек не уходил, и Дмитрий вышел, забрав папку с собой.',
      'В итоге у него только семь снимков, а исчезновение папки заметят.',
    ],
    modelRetelling:
      'A man called Dmitri went into a colleague\'s office at night to photograph a file. He had eight minutes between the cleaner leaving and the security guard\'s round. He found the folder and started taking photos, but somebody came up in the lift and went into the room next door. The person did not leave, so Dmitri took the folder and walked out. He only had seven of the twelve pages, and the missing folder would be noticed soon.',
    discussion: [
      'Do you like stories where you know something bad is going to happen?',
      'Have you ever had a plan that went wrong at the last moment?',
      'What do you think Dmitri should do next?',
    ],
    glossary: {
      cleaner: { t: 'уборщица' },
      guard: { t: 'охранник' },
      counted: { t: 'просчитал', l: 'count' },
      route: { t: 'маршрут' },
      bored: { t: 'скучающий' },
      lock: { t: 'замок' },
      drawer: { t: 'ящик стола' },
      accident: { t: 'происшествие, авария' },
      fault: { t: 'вина' },
      folder: { t: 'папка' },
      colleague: { t: 'коллега' },
      described: { t: 'описал', l: 'describe' },
      pens: { t: 'ручки', l: 'pen' },
      photograph: { t: 'фотографировать' },
      steady: { t: 'твёрдый, ровный' },
      lamp: { t: 'лампа' },
      shoes: { t: 'ботинки', l: 'shoe' },
      coughed: { t: 'кашлянул', l: 'cough' },
      silence: { t: 'тишина' },
      shirt: { t: 'рубашка' },
      picked: { t: 'взял', l: 'pick', n: 'pick up — поднять, взять' },
      missing: { t: 'недостающие', l: 'miss' },
      notice: { t: 'заметить' },
      planned: { t: 'спланировал', l: 'plan' },
    },
  },

  {
    id: 'one-memory',
    title: 'One Memory, Please',
    topic: 'сервис, который стирает одно воспоминание',
    genre: { id: 'scifi', label: 'Фантастика', emoji: '🛰️' },
    imagePrompt: 'a calm modern clinic waiting room with soft light and one empty chair',
    paragraphs: [
      '**The clinic looked like a dentist\'s: white chairs, a plant, a woman at a desk asking if you had eaten this morning.** The service was legal, cheap and popular. One memory, chosen by you, described in your own words, gone in forty minutes. People came before weddings, after funerals, on ordinary Tuesdays. The waiting room was always half full and always very quiet.',
      'Vera came for the fourth of August. She wrote it on the form the way you write an address: the kitchen, the phone in her hand, her sister\'s voice saying the words that changed the shape of everything after. She did not want to forget her sister. She wanted to forget the four minutes of that call. The doctor said this was the most common request they received.',
      'Afterwards she felt nothing at all, which was the point. She went home, made tea, watered the plants. Two days later a friend mentioned the date, and Vera heard herself answer calmly, kindly, like a person reading from a card. She knew what had happened. She simply could not find the place where it hurt.',
      'The problem came in October. Her sister\'s birthday arrived and Vera felt nothing there either. It turned out that the four minutes had been holding other things: the smell of that kitchen, the last joke they had shared, why she had started calling her mother every Sunday. When you pull one thread out of cloth, you do not get a smaller piece of cloth. You get a hole and a lot of loose ends.',
      '**They tell you that the memory is a room you can close. Nobody tells you that the door was holding up the wall.**',
    ],
    questions: [
      {
        question: 'What service does the clinic offer?',
        options: [
          'It repairs teeth',
          'It removes one chosen memory',
          'It records your dreams',
          'It gives you new memories',
        ],
        correctIndex: 1,
        explanation: 'Одно воспоминание по вашему выбору стирается за сорок минут.',
      },
      {
        question: 'What exactly did Vera want to forget?',
        options: [
          'Her sister',
          'Her whole childhood',
          'The four minutes of a phone call',
          'The clinic itself',
        ],
        correctIndex: 2,
        explanation: 'Она не хотела забыть сестру — только те четыре минуты разговора.',
      },
      {
        question: 'What did Vera discover in October?',
        options: [
          'The memory came back',
          'Other memories had disappeared with it',
          'The clinic had closed',
          'Her sister was still alive',
        ],
        correctIndex: 1,
        explanation: 'Вместе с теми минутами ушли запах кухни, последняя шутка и другие связи.',
      },
      {
        question: 'What does the last line mean?',
        options: [
          'Doors are dangerous',
          'The clinic was badly built',
          'A painful memory can be holding other things together',
          'You should never close a door',
        ],
        correctIndex: 2,
        explanation: 'Дверь держала стену: болезненное воспоминание держало на себе многое другое.',
      },
    ],
    keyPoints: [
      'В клинике за сорок минут стирают одно воспоминание по выбору клиента.',
      'Вера пришла стереть четыре минуты телефонного разговора, а не саму сестру.',
      'После процедуры она ничего не чувствовала — и это было целью.',
      'В октябре выяснилось, что вместе с теми минутами исчезли и другие связанные воспоминания.',
      'Вывод: болезненное воспоминание нередко держит на себе многое другое.',
    ],
    modelRetelling:
      'In this story there is a clinic where you can pay to delete one memory. A woman called Vera wants to forget four minutes of a phone call about her sister, but not her sister herself. After the procedure she feels nothing about that day. Later she understands that other memories have gone too — small details and reasons connected to those minutes. The story says that a painful memory can hold other parts of your life together.',
    discussion: [
      'If this service existed, would you use it? Why or why not?',
      'Do you think painful memories can be useful?',
      'What everyday technology today changes how we remember things?',
    ],
    glossary: {
      clinic: { t: 'клиника' },
      dentist: { t: 'стоматолог' },
      legal: { t: 'законный' },
      popular: { t: 'популярный' },
      chosen: { t: 'выбранный', l: 'choose' },
      described: { t: 'описанный', l: 'describe' },
      weddings: { t: 'свадьбы', l: 'wedding' },
      funerals: { t: 'похороны', l: 'funeral' },
      ordinary: { t: 'обычный' },
      form: { t: 'бланк, анкета' },
      voice: { t: 'голос' },
      shape: { t: 'форма' },
      request: { t: 'запрос, просьба' },
      received: { t: 'получали', l: 'receive' },
      afterwards: { t: 'потом, после' },
      watered: { t: 'полила', l: 'water' },
      mentioned: { t: 'упомянул', l: 'mention' },
      calmly: { t: 'спокойно' },
      kindly: { t: 'мягко, по-доброму' },
      hurt: { t: 'болеть' },
      birthday: { t: 'день рождения' },
      holding: { t: 'держали', l: 'hold' },
      joke: { t: 'шутка' },
      thread: { t: 'нитка' },
      cloth: { t: 'ткань' },
      hole: { t: 'дыра' },
      loose: { t: 'свободный, болтающийся' },
      ends: { t: 'концы', l: 'end' },
    },
  },

  {
    id: 'rain-tuesdays',
    title: 'It Only Rains on Tuesdays',
    topic: 'город со странным расписанием дождя',
    genre: { id: 'weird', label: 'Странное', emoji: '🌀' },
    imagePrompt: 'a small town street under heavy rain, people calmly carrying identical umbrellas',
    paragraphs: [
      '**In Marnow it rains on Tuesdays. Not usually, not mostly. On Tuesdays.** Nobody in the town finds this strange, and visitors who mention it are answered politely and briefly, the way you answer a child who has noticed that water is wet. The rain begins at about six in the morning and stops before midnight, and the other six days are dry.',
      'The town is built around this. Weddings are never held on a Tuesday. The market moves to Wednesday. Farmers plant according to a calendar their grandparents wrote, and the football club plays at home on Saturdays because the grass has had four days to drink. Children own one coat, not two, and everyone owns the same grey umbrella, which is sold in the shop by the station for nine euros.',
      'A journalist came from the capital in April to write about it. She stayed eleven days, asked ninety questions, and left with almost nothing. The mayor told her, kindly, that people had been asking the same question for a hundred years and it had never yet made anything grow. The baker said he did not know why it rained on Tuesdays, and asked her why it rained on any day at all.',
      'What the journalist could not explain to her editor was the feeling she took home with her. In Marnow, one day of the week is spoken for. You cannot decide to go to the lake on Tuesday; the lake is not available. And so people plan the other six days with a care she had never seen in the city, where every day looks possible and most of them disappear.',
      '**She did not write the article about the rain. She wrote it about the six dry days, and her editor said it was the best thing she had ever done, and asked her, at the end, whether the story about the rain was true.**',
    ],
    questions: [
      {
        question: 'What is unusual about Marnow?',
        options: [
          'It never rains there',
          'It rains only on Tuesdays',
          'It rains every day',
          'It rains at night only',
        ],
        correctIndex: 1,
        explanation: 'Дождь идёт по вторникам — не «обычно», а именно по вторникам.',
      },
      {
        question: 'How do the people of Marnow react to this?',
        options: [
          'They are frightened',
          'They treat it as completely normal',
          'They try to stop it',
          'They leave the town',
        ],
        correctIndex: 1,
        explanation: 'Никто не считает это странным; приезжим отвечают вежливо и коротко.',
      },
      {
        question: 'What did the journalist finally write about?',
        options: [
          'The rain itself',
          'The mayor',
          'The six dry days and how people use them',
          'The price of umbrellas',
        ],
        correctIndex: 2,
        explanation: 'Статья вышла не про дождь, а про шесть сухих дней.',
      },
      {
        question: 'What is the deeper idea of the story?',
        options: [
          'Small towns are boring',
          'Weather controls our lives',
          'A limit can make people value the time they have',
          'Journalists ask too many questions',
        ],
        correctIndex: 2,
        explanation: 'Один занятый день заставляет планировать остальные шесть с настоящей заботой.',
      },
    ],
    keyPoints: [
      'В городке Марнов дождь идёт только по вторникам, и никого это не удивляет.',
      'Весь уклад подстроен под это: рынок по средам, свадьбы не во вторник, у всех одинаковые зонты.',
      'Журналистка приехала разбираться и за одиннадцать дней ничего не выяснила.',
      'Её поразило другое: раз один день недели «занят», остальные шесть планируют очень бережно.',
      'Она написала статью не про дождь, а про шесть сухих дней.',
    ],
    modelRetelling:
      'The story is about a small town where it rains only on Tuesdays. The people there think this is completely normal and have built their life around it: the market is on Wednesday, nobody gets married on Tuesday, and everyone has the same umbrella. A journalist came to find the reason and learned nothing. What surprised her was that people planned their other six days very carefully, and she wrote her article about that instead.',
    discussion: [
      'Would you like to live in a town like Marnow? Why or why not?',
      'Do you plan your week, or do you decide day by day?',
      'Is it easier to enjoy free time when you have less of it?',
    ],
    glossary: {
      mostly: { t: 'в основном' },
      visitors: { t: 'приезжие', l: 'visitor' },
      briefly: { t: 'коротко' },
      midnight: { t: 'полночь' },
      dry: { t: 'сухой' },
      built: { t: 'построен', l: 'build' },
      weddings: { t: 'свадьбы', l: 'wedding' },
      market: { t: 'рынок' },
      farmers: { t: 'фермеры', l: 'farmer' },
      plant: { t: 'сажать' },
      according: { t: 'согласно', n: 'according to — согласно чему-то' },
      grandparents: { t: 'бабушки и дедушки' },
      grass: { t: 'трава' },
      coat: { t: 'куртка, пальто' },
      umbrella: { t: 'зонт' },
      station: { t: 'вокзал' },
      journalist: { t: 'журналистка' },
      capital: { t: 'столица' },
      mayor: { t: 'мэр' },
      baker: { t: 'пекарь' },
      editor: { t: 'редактор' },
      available: { t: 'доступный, свободный' },
      care: { t: 'забота, внимательность' },
      article: { t: 'статья' },
      whether: { t: 'ли' },
    },
  },

  {
    id: 'saying-no',
    title: 'The First No',
    topic: 'как впервые сказать «нет»',
    genre: { id: 'motivation', label: 'Мотивация', emoji: '🌱' },
    imagePrompt: 'a quiet office desk with a phone face down and a cup of tea, warm afternoon light',
    paragraphs: [
      '**Some people are not tired because they work too much. They are tired because they have never once said no.** Katya was that person for eleven years. She stayed late for colleagues who asked nicely. She helped her cousin move flat twice in one summer. She said yes on Friday evening to things she had already refused inside her head on Friday morning.',
      'It was never about kindness, although it looked like kindness from outside. It was about a small fear that lived under every conversation: if I say no, this person will decide I am difficult, and later, when I need something, nobody will be there. Saying yes was how she paid for a safety she never actually tested.',
      'The first no was small and badly done. A manager asked her to take a report on a Friday afternoon, and Katya heard herself say, "I can\'t do it today, but I can do it on Monday morning." Her voice was too high. She waited for the sky to fall. The manager said, "Fine, Monday," and walked away thinking about something else entirely.',
      'Nothing happened, and that was the strangest part. Over the next months she said no perhaps twenty times, and the world stayed exactly where it was. Two people were annoyed, briefly. One friendship became honest for the first time in years. And Katya noticed something she had not expected: her yes started to mean something, to her and to everyone else.',
      '**A no is not a wall you build against people. It is the fence around the small garden where your yes still grows.**',
    ],
    questions: [
      {
        question: 'Why was Katya always tired?',
        options: [
          'She had two jobs',
          'She never said no to anyone',
          'She slept badly',
          'She travelled a lot',
        ],
        correctIndex: 1,
        explanation: 'Она устала не от работы, а от того, что никогда не отказывала.',
      },
      {
        question: 'What was the real reason she always said yes?',
        options: [
          'She loved helping',
          'She wanted more money',
          'She was afraid that people would not be there when she needed them',
          'Her manager forced her',
        ],
        correctIndex: 2,
        explanation: 'Под этим лежал страх: откажу — и потом никто не поможет мне.',
      },
      {
        question: 'What happened after her first no?',
        options: [
          'She lost her job',
          'The manager was angry',
          'Practically nothing happened',
          'She had to work on Saturday',
        ],
        correctIndex: 2,
        explanation: 'Менеджер сказал «хорошо, в понедельник» и ушёл — и это оказалось самым удивительным.',
      },
      {
        question: 'What does the fence in the last line mean?',
        options: [
          'You should keep people away',
          'Saying no protects the things you really agree to',
          'Gardens need protection',
          'Walls are better than fences',
        ],
        correctIndex: 1,
        explanation: '«Нет» защищает то место, где ваше «да» ещё что-то значит.',
      },
    ],
    keyPoints: [
      'Катя одиннадцать лет соглашалась на всё и всегда была уставшей.',
      'Причина была не в доброте, а в страхе: откажу — и потом мне никто не поможет.',
      'Первое «нет» вышло неловким: она предложила сделать отчёт в понедельник вместо пятницы.',
      'Ничего страшного не случилось — менеджер просто согласился.',
      'За несколько месяцев она отказала раз двадцать, и её «да» начало что-то значить.',
    ],
    modelRetelling:
      'The text is about a woman who could never say no. She stayed late at work and helped everyone, and she was always tired. The real reason was fear: she thought that if she refused, nobody would help her later. One Friday she told her manager that she could do a report on Monday instead, and nothing bad happened. After a few months of saying no sometimes, her life did not fall apart, and her yes began to mean more.',
    discussion: [
      'Is it easy for you to say no? In which situations is it hardest?',
      'Have you ever said yes to something and regretted it immediately?',
      'How do you feel when somebody says no to you politely?',
    ],
    glossary: {
      colleagues: { t: 'коллеги', l: 'colleague' },
      nicely: { t: 'вежливо, мило' },
      cousin: { t: 'двоюродный брат/сестра' },
      refused: { t: 'отказала', l: 'refuse' },
      kindness: { t: 'доброта' },
      although: { t: 'хотя' },
      fear: { t: 'страх' },
      difficult: { t: 'сложный (о человеке — неудобный)' },
      paid: { t: 'платила', l: 'pay' },
      safety: { t: 'безопасность' },
      tested: { t: 'проверяла', l: 'test' },
      badly: { t: 'плохо' },
      manager: { t: 'начальник' },
      report: { t: 'отчёт' },
      voice: { t: 'голос' },
      entirely: { t: 'совершенно' },
      strangest: { t: 'самое странное', l: 'strange' },
      annoyed: { t: 'раздражены', l: 'annoy' },
      briefly: { t: 'ненадолго' },
      honest: { t: 'честный' },
      expected: { t: 'ожидала', l: 'expect' },
      fence: { t: 'забор, ограда' },
      garden: { t: 'сад' },
      grows: { t: 'растёт', l: 'grow' },
    },
  },
];
