/** Тексты 21–25. */
export default [
  {
    id: 'photo-twice',
    title: 'The Photograph',
    topic: 'снимок, на котором один человек дважды',
    genre: { id: 'horror', label: 'Ужастик', emoji: '🕯️' },
    imagePrompt: 'an old family photograph on a table, one figure blurred at the edge, cold light',
    paragraphs: [
      '**The photograph had been in the album for nineteen years before anybody counted the people in it.** It was taken at Lena\'s grandmother\'s house in July: eleven relatives on the steps, squinting, holding plates. Lena scanned it for her mother\'s birthday and looked at it properly for the first time on a large screen, at half past eleven at night, with the file open beside her tea.',
      'Her uncle Vitya stood in the middle, in a white shirt, laughing at something to the left. Her uncle Vitya also stood at the end of the back row, not laughing, looking directly into the camera. The two men had the same face, the same shirt and the same watch. In the second one the shirt was wet along the shoulder, as if he had come from somewhere else entirely.',
      'She called her mother, who was calm about it in a way that was worse than shouting. Her mother said that Vitya had drowned four years before that summer, and that the family had agreed, without ever discussing it, never to mention his name in front of the grandmother. Then she asked Lena to send the file, and then she asked her not to.',
      'Lena printed it anyway. In the printed copy the man at the end of the back row is there, and everybody who looks at it sees him, and nobody has an explanation. Her mother keeps the print in a drawer and takes it out perhaps twice a year, and each time she says the same thing: he is standing a little closer to the others than he was.',
      '**Lena has stopped checking. She knows that if she measures the distance in the photograph, one of two things will be true, and she has decided she does not want to know which.**',
    ],
    questions: [
      {
        question: 'What did Lena notice on the photograph?',
        options: [
          'A stranger in the garden',
          'Her uncle appears twice',
          'Her grandmother is missing',
          'The date is wrong',
        ],
        correctIndex: 1,
        explanation: 'Дядя Витя стоит и в середине, и в заднем ряду — с тем же лицом, рубашкой и часами.',
      },
      {
        question: 'What was different about the second figure?',
        options: [
          'He was much older',
          'He was holding a plate',
          'His shirt was wet on the shoulder and he was not laughing',
          'He stood in the doorway',
        ],
        correctIndex: 2,
        explanation: 'Второй не смеялся, смотрел в камеру, а рубашка была мокрой на плече.',
      },
      {
        question: 'What did her mother say?',
        options: [
          'That it was a printing mistake',
          'That Vitya had drowned four years earlier',
          'That she had never met Vitya',
          'That the photograph was from another family',
        ],
        correctIndex: 1,
        explanation: 'Витя утонул за четыре года до того лета, и в семье не произносили его имя.',
      },
      {
        question: 'Why has Lena stopped checking the photograph?',
        options: [
          'She lost it',
          'She does not want to know whether the figure moves',
          'Her mother forbade it',
          'The print faded',
        ],
        correctIndex: 1,
        explanation: 'Она понимает: измерив расстояние, узнает один из двух ответов — и не хочет ни одного.',
      },
    ],
    keyPoints: [
      'Лена оцифровала старую семейную фотографию и разглядела её на большом экране.',
      'Дядя Витя оказался на снимке дважды: в середине и в заднем ряду, с мокрым плечом.',
      'Мать спокойно сказала, что Витя утонул за четыре года до того лета.',
      'На отпечатке фигуру видят все, объяснить никто не может.',
      'Мать уверяет, что он стоит всё ближе к остальным, а Лена перестала проверять.',
    ],
    modelRetelling:
      'A woman scanned an old family photograph and saw that her uncle appeared twice in it. One figure was laughing in the middle of the group, and the other stood at the back, looking at the camera, with a wet shirt. Her mother told her that this uncle had drowned four years before the photograph was taken. Everybody who looks at the print can see him, and the mother believes he is slowly moving closer to the family.',
    discussion: [
      'Do you have old family photographs at home? Do you look at them often?',
      'Would you keep such a photograph or destroy it?',
      'Why do you think people find old pictures frightening?',
    ],
    glossary: {
      album: { t: 'альбом' },
      counted: { t: 'пересчитал', l: 'count' },
      relatives: { t: 'родственники', l: 'relative' },
      steps: { t: 'ступеньки', l: 'step' },
      squinting: { t: 'щурясь', l: 'squint' },
      plates: { t: 'тарелки', l: 'plate' },
      scanned: { t: 'отсканировала', l: 'scan' },
      properly: { t: 'как следует' },
      uncle: { t: 'дядя' },
      row: { t: 'ряд' },
      directly: { t: 'прямо' },
      camera: { t: 'камера, фотоаппарат' },
      watch: { t: 'наручные часы' },
      shoulder: { t: 'плечо' },
      entirely: { t: 'совершенно' },
      shouting: { t: 'крик', l: 'shout' },
      drowned: { t: 'утонул', l: 'drown' },
      agreed: { t: 'договорились', l: 'agree' },
      discussing: { t: 'обсуждая', l: 'discuss' },
      mention: { t: 'упоминать' },
      printed: { t: 'напечатала', l: 'print' },
      copy: { t: 'копия' },
      drawer: { t: 'ящик' },
      measures: { t: 'измерит', l: 'measure' },
      distance: { t: 'расстояние' },
    },
  },

  {
    id: 'timetable-alibi',
    title: 'The Alibi and the Timetable',
    topic: 'алиби, построенное на расписании поездов',
    genre: { id: 'mystery', label: 'Детектив', emoji: '🔎' },
    imagePrompt: 'a small railway station platform at dusk with an old departure board',
    paragraphs: [
      '**A good alibi is a story that other people can check. A perfect one is a story that other people have already checked for you.** When the safe at the printing works was emptied on a Thursday evening, the manager, Andrei Kotov, was on a train. He said so at once, produced a ticket for the 18:40, and named the two people who had seen him at the far station at 19:55.',
      'Both witnesses were honest and neither of them was wrong. The ticket was real. The train had run, and it had carried a man who looked exactly like Kotov, because it had carried Kotov. Sergeant Volkova checked the timetable three times, and each time the numbers agreed with the story, which is the point at which she started to be interested rather than satisfied.',
      'What she looked at next was not the timetable but the timetable\'s history. Since the twelfth of that month the 18:40 had been leaving twelve minutes late every day, because of work on the line, and every regular passenger knew it. A man planning a journey around a printed schedule would not know. A man planning something else around the same schedule would find the delay very convenient indeed.',
      'Kotov had been at the works until 18:44 — four minutes after his train was supposed to leave, and eight before it actually did. The station was two hundred metres from the gate. Volkova did not accuse him of anything. She simply asked, in front of his wife, why he had told her three times that he caught the train at 18:40 exactly, when nobody in that town had caught it at 18:40 for two weeks.',
      '**Most liars are careful with the facts they invent. They are careless with the facts everybody else lives inside.**',
    ],
    questions: [
      {
        question: 'What was Kotov\'s alibi?',
        options: [
          'He was at home with his wife',
          'He was on the 18:40 train and was seen at the far station',
          'He was in another town all week',
          'He was in hospital',
        ],
        correctIndex: 1,
        explanation: 'Он предъявил билет на 18:40 и назвал двух свидетелей на конечной станции.',
      },
      {
        question: 'What was true about the witnesses?',
        options: [
          'They lied for money',
          'They were honest and not mistaken',
          'They did not exist',
          'They were his relatives',
        ],
        correctIndex: 1,
        explanation: 'Оба свидетеля были честны и не ошибались — и это делало дело интереснее.',
      },
      {
        question: 'What had changed about the 18:40 train?',
        options: [
          'It had been cancelled',
          'It left twelve minutes late every day because of work on the line',
          'It stopped at a different station',
          'It had become more expensive',
        ],
        correctIndex: 1,
        explanation: 'С двенадцатого числа поезд ежедневно уходил на двенадцать минут позже.',
      },
      {
        question: 'Why did that detail give him away?',
        options: [
          'He arrived too early',
          'He insisted on the printed time that nobody actually travelled by',
          'He had no ticket',
          'The witnesses changed their story',
        ],
        correctIndex: 1,
        explanation: 'Он трижды повторил «ровно 18:40» — время, в которое уже две недели никто не уезжал.',
      },
    ],
    keyPoints: [
      'В четверг вечером обчистили сейф в типографии, а управляющий Котов предъявил алиби: поезд 18:40.',
      'Свидетели были честны, билет настоящий, расписание сходилось.',
      'Сержант Волкова проверила не расписание, а его историю: две недели поезд уходил на 12 минут позже.',
      'Котов был на работе до 18:44 — уже после «отправления», но до реального.',
      'Он трижды настаивал на времени из печатного расписания, которым в городе никто не пользовался.',
    ],
    modelRetelling:
      'A safe was emptied at a printing works, and the manager said he had been on the 18:40 train. He had a real ticket and two honest witnesses who saw him at the other station. The sergeant checked the timetable and everything matched, but then she found out that for two weeks the train had been leaving twelve minutes late. The manager was at work until 18:44, and he kept insisting on the printed time, which nobody in the town used any more.',
    discussion: [
      'Do you like detective stories where the answer is hidden in ordinary details?',
      'Have you ever noticed that a timetable or a rule and real life do not match?',
      'What would you have asked Kotov?',
    ],
    glossary: {
      alibi: { t: 'алиби' },
      timetable: { t: 'расписание' },
      printing: { t: 'типографский', l: 'print' },
      works: { t: 'производство, завод' },
      emptied: { t: 'опустошён', l: 'empty' },
      produced: { t: 'предъявил', l: 'produce' },
      ticket: { t: 'билет' },
      witnesses: { t: 'свидетели', l: 'witness' },
      honest: { t: 'честный' },
      sergeant: { t: 'сержант' },
      agreed: { t: 'сходились', l: 'agree' },
      satisfied: { t: 'удовлетворённый' },
      twelfth: { t: 'двенадцатое (число)' },
      line: { t: 'путь, линия' },
      regular: { t: 'постоянный' },
      passenger: { t: 'пассажир' },
      journey: { t: 'поездка' },
      schedule: { t: 'расписание' },
      convenient: { t: 'удобный' },
      gate: { t: 'ворота' },
      accuse: { t: 'обвинять' },
      caught: { t: 'успел на', l: 'catch' },
      liars: { t: 'лжецы', l: 'liar' },
      invent: { t: 'выдумывать' },
      careless: { t: 'небрежный' },
    },
  },

  {
    id: 'two-turns',
    title: 'Two Turns Too Many',
    topic: 'машина, которая едет за тобой',
    genre: { id: 'thriller', label: 'Триллер', emoji: '⏱️' },
    imagePrompt: 'headlights of a car in a rear-view mirror on a wet night road',
    paragraphs: [
      '**The first turn means nothing. The second turn means nothing. It is the third that changes the evening.** Dasha left the supermarket at ten past nine and noticed the dark blue car at the roundabout, because it was too far back and did not overtake when the road opened. She told herself the sensible thing: half the town drives home this way.',
      'At the second turn it was still there, four cars behind, keeping the same distance the way a driver does when distance is the point. Dasha went past her own street and took the long route along the river. So did the blue car. Her hands were cold, and she noticed that she had started to plan, which she had not decided to do: petrol station, lights, people, camera.',
      'She turned into the station and stopped by the door, in the brightest place she could find. The blue car came in behind her, drove slowly past the pumps and stopped at the far end, engine running, lights off. Nobody got out. Dasha sat with her doors locked and called her brother, who lived eleven minutes away, and told him where she was in a voice that surprised her by being steady.',
      'When his headlights came round the corner, the blue car left immediately, unhurried, indicating properly at the exit. It did not pass her again. She reported it, gave four digits of a number plate that turned out to belong to a car that had been sold twice that year, and nothing came of it. Nothing ever came of it.',
      '**She still drives the long way home sometimes, for no reason she can defend. Once you have learned that a road can be shared with somebody who is counting your turns, you never quite un-learn it.**',
    ],
    questions: [
      {
        question: 'What first made Dasha notice the blue car?',
        options: [
          'It was very loud',
          'It stayed far back and did not overtake',
          'It flashed its lights',
          'It was parked outside her house',
        ],
        correctIndex: 1,
        explanation: 'Машина держалась слишком далеко и не обгоняла, когда дорога освободилась.',
      },
      {
        question: 'What did she do instead of going home?',
        options: [
          'She drove to the police station',
          'She went past her street and took the long route',
          'She stopped in the middle of the road',
          'She drove to her brother\'s flat',
        ],
        correctIndex: 1,
        explanation: 'Она проехала мимо своей улицы и поехала длинной дорогой вдоль реки.',
      },
      {
        question: 'What happened at the petrol station?',
        options: [
          'The driver came to her window',
          'The blue car stopped at the far end with its lights off',
          'The car drove away at once',
          'She lost sight of the car',
        ],
        correctIndex: 1,
        explanation: 'Синяя машина проехала мимо колонок и встала в дальнем конце с работающим мотором.',
      },
      {
        question: 'How does the story end?',
        options: [
          'The driver is caught',
          'Nothing is proved and the number plate leads nowhere',
          'She moves to another town',
          'Her brother follows the car',
        ],
        correctIndex: 1,
        explanation: 'Номер оказался от машины, дважды перепроданной за год, и дело ничем не кончилось.',
      },
    ],
    keyPoints: [
      'Даша заметила синюю машину, которая держалась позади и не обгоняла.',
      'Она проехала мимо своей улицы и поехала длинной дорогой — машина повторила манёвр.',
      'Даша остановилась на заправке в самом освещённом месте и вызвала брата.',
      'Синяя машина встала в дальнем конце с выключенными фарами, из неё никто не вышел.',
      'Она уехала, как только появился брат; номер ни к чему не привёл.',
    ],
    modelRetelling:
      'A woman was driving home from the supermarket when she noticed a dark blue car behind her. It kept the same distance and followed her when she took a longer route. She stopped at a petrol station in a bright place, and the car came in too and waited at the far end with its lights off. She locked her doors and called her brother, and when he arrived the car left calmly. The police could not trace the number plate.',
    discussion: [
      'Have you ever felt that somebody was following you? What did you do?',
      'What would you have done in Dasha\'s place?',
      'Do you feel safe walking or driving alone at night in your town?',
    ],
    glossary: {
      turn: { t: 'поворот' },
      supermarket: { t: 'супермаркет' },
      roundabout: { t: 'круговое движение' },
      overtake: { t: 'обгонять' },
      sensible: { t: 'разумный' },
      distance: { t: 'дистанция' },
      route: { t: 'маршрут' },
      petrol: { t: 'бензин', n: 'petrol station — заправка' },
      station: { t: 'станция; заправка' },
      brightest: { t: 'самый освещённый', l: 'bright' },
      pumps: { t: 'колонки (заправочные)', l: 'pump' },
      engine: { t: 'двигатель' },
      locked: { t: 'запертый', l: 'lock' },
      steady: { t: 'ровный, твёрдый' },
      headlights: { t: 'фары' },
      immediately: { t: 'сразу' },
      unhurried: { t: 'неторопливо' },
      indicating: { t: 'показывая поворот', l: 'indicate' },
      exit: { t: 'выезд' },
      reported: { t: 'сообщила', l: 'report' },
      digits: { t: 'цифры', l: 'digit' },
      plate: { t: 'номерной знак', n: 'number plate — номер машины' },
      defend: { t: 'защищать, объяснить' },
      counting: { t: 'считает', l: 'count' },
    },
  },

  {
    id: 'what-you-notice',
    title: 'What Your Brain Decides to Notice',
    topic: 'почему мы видим не всё, что перед нами',
    genre: { id: 'science', label: 'Научпоп', emoji: '🔬' },
    imagePrompt: 'a busy street scene with one object in sharp focus and the rest soft, minimal illustration',
    paragraphs: [
      '**Your eyes send far more information to your brain than your brain is willing to pay for.** Every second, the world offers millions of details: edges, colours, movements, sounds. Only a small part of that becomes experience. The rest is thrown away before you know it existed, and the rules for throwing it away are not chosen by you.',
      'The famous experiment is simple. People watch a short film of players passing a ball and count the passes. About half of them do not see a person in a gorilla suit walk slowly through the middle of the screen, stop, and wave. When the film is played again, they often argue that it is a different film. Their eyes pointed at the gorilla. Their attention did not.',
      'This is not a fault. Attention works like a narrow door with a guard, and the guard has instructions: whatever the person is doing right now, let that through first. It is the reason a driver can miss a motorbike while looking straight at it, and also the reason a mother wakes at the smallest sound from a child and sleeps through a storm.',
      'The useful part is that the instructions can be changed, at least a little. Learning a bird\'s song makes you hear that bird for the rest of your life. Learning the name of a building style makes those buildings appear in a city you have walked through for years. Nothing new arrives in the street. The guard simply gets a new line on the list.',
      '**You are not seeing the world. You are seeing the small part of it that your current task has made important — which is why a new interest can feel exactly like moving to a new city.**',
    ],
    questions: [
      {
        question: 'What happens to most of the information from your eyes?',
        options: [
          'It is stored for later',
          'It is thrown away before you notice it',
          'It is sent to memory',
          'It is used for dreams',
        ],
        correctIndex: 1,
        explanation: 'Большая часть отбрасывается ещё до того, как вы узнаёте о её существовании.',
      },
      {
        question: 'What happens in the gorilla experiment?',
        options: [
          'People count the passes wrongly',
          'About half do not see the gorilla at all',
          'Everybody sees the gorilla immediately',
          'The film is too short to follow',
        ],
        correctIndex: 1,
        explanation: 'Около половины зрителей не замечают человека в костюме гориллы.',
      },
      {
        question: 'How does the writer describe attention?',
        options: [
          'As a camera',
          'As a narrow door with a guard who has instructions',
          'As a locked room',
          'As a river',
        ],
        correctIndex: 1,
        explanation: 'Узкая дверь с охранником, у которого есть инструкции: пропускать нужное для текущего дела.',
      },
      {
        question: 'What is the practical conclusion?',
        options: [
          'You should look more carefully',
          'Learning something new changes what you notice',
          'Attention cannot be changed',
          'Experiments are unreliable',
        ],
        correctIndex: 1,
        explanation: 'Выучив название птицы или стиля зданий, вы начинаете замечать их всюду.',
      },
    ],
    keyPoints: [
      'Глаза отправляют мозгу гораздо больше информации, чем он готов обрабатывать.',
      'В известном опыте половина зрителей не замечает человека в костюме гориллы.',
      'Внимание работает как узкая дверь с охранником: пропускается то, что нужно для текущего дела.',
      'Поэтому водитель может не увидеть мотоцикл, а мать просыпается от тихого звука ребёнка.',
      'Инструкции можно менять: выучив что-то новое, начинаешь это замечать повсюду.',
    ],
    modelRetelling:
      'The text explains that we notice only a small part of what our eyes see. In a famous experiment, people counting passes in a film do not see a person in a gorilla suit walking across the screen. The writer compares attention to a narrow door with a guard who lets through only what is useful for the task at the moment. The good news is that we can change these instructions: when you learn about something, you start noticing it everywhere.',
    discussion: [
      'Have you ever completely missed something that was in front of you?',
      'Is there something you started noticing after you learned about it?',
      'Do you think we should try to notice more, or is filtering useful?',
    ],
    glossary: {
      willing: { t: 'готовый' },
      offers: { t: 'предлагает', l: 'offer' },
      millions: { t: 'миллионы', l: 'million' },
      edges: { t: 'края, контуры', l: 'edge' },
      movements: { t: 'движения', l: 'movement' },
      experience: { t: 'опыт, переживание' },
      thrown: { t: 'выброшен', l: 'throw' },
      rules: { t: 'правила', l: 'rule' },
      famous: { t: 'знаменитый' },
      experiment: { t: 'эксперимент' },
      players: { t: 'игроки', l: 'player' },
      passes: { t: 'передачи', l: 'pass' },
      gorilla: { t: 'горилла' },
      suit: { t: 'костюм' },
      argue: { t: 'спорить, утверждать' },
      attention: { t: 'внимание' },
      fault: { t: 'недостаток, вина' },
      narrow: { t: 'узкий' },
      guard: { t: 'охранник' },
      instructions: { t: 'инструкции' },
      motorbike: { t: 'мотоцикл' },
      storm: { t: 'гроза, буря' },
      style: { t: 'стиль' },
      arrives: { t: 'появляется', l: 'arrive' },
      current: { t: 'текущий' },
    },
  },

  {
    id: 'taxi-story',
    title: 'The Taxi Driver',
    topic: 'случайный разговор в дороге',
    genre: { id: 'life', label: 'Из жизни', emoji: '☕' },
    imagePrompt: 'a taxi interior at night, city lights passing the window, warm dashboard glow',
    paragraphs: [
      '**The best conversations of your life will happen with people you will never see again.** Igor got into the taxi at half past five in the morning, going to the airport, in the state where you are awake but not yet a person. The driver said good morning, asked nothing else, and drove. For eleven minutes there was only the sound of the road and the indicator.',
      'Then Igor asked, mostly to be polite, how long the man had been driving at night. Twenty-two years, said the driver. He had been an engineer in a factory that closed in the nineties, and he had planned to drive for six months while he looked for something proper. He said this without any bitterness at all, which was the thing Igor kept thinking about later.',
      'They talked about his daughter, who was a doctor in another city, and about the fact that he had learned every road in the region so well that he no longer used the navigator, and that this was now a completely useless skill and he was proud of it anyway. He said the worst passengers were not the drunk ones but the ones who talked to somebody else on the phone about how stupid the driver was, in a language they assumed he did not speak.',
      'At the airport Igor paid, and then stood for a second with the door open, wanting to say something that would be adequate, and said thank you, which was not. He does not remember the man\'s face now, only his hands on the wheel and the fact that he had described twenty-two years as a period he had chosen, not a period that had happened to him.',
      '**Ask one real question of a stranger and you may get a whole life in return, told plainly, by somebody who has no reason to make it sound better than it was.**',
    ],
    questions: [
      {
        question: 'Why was Igor in the taxi?',
        options: ['Going to work', 'Going to the airport', 'Going home from a party', 'Meeting his family'],
        correctIndex: 1,
        explanation: 'Он ехал в аэропорт в половине шестого утра.',
      },
      {
        question: 'What had the driver done before?',
        options: [
          'He was a teacher',
          'He was an engineer in a factory that closed',
          'He drove a bus',
          'He worked at the airport',
        ],
        correctIndex: 1,
        explanation: 'Он был инженером на заводе, который закрылся в девяностые.',
      },
      {
        question: 'What surprised Igor about him?',
        options: [
          'He complained a lot',
          'He spoke without any bitterness',
          'He drove very fast',
          'He refused to talk',
        ],
        correctIndex: 1,
        explanation: 'В его словах не было ни капли горечи — именно это Игорь потом вспоминал.',
      },
      {
        question: 'What is the main idea of the last paragraph?',
        options: [
          'You should always tip taxi drivers',
          'A real question to a stranger can bring an honest life story',
          'Strangers rarely tell the truth',
          'Night work is difficult',
        ],
        correctIndex: 1,
        explanation: 'Один настоящий вопрос — и человек рассказывает жизнь без прикрас.',
      },
    ],
    keyPoints: [
      'Игорь ехал в аэропорт в половине шестого утра и первые одиннадцать минут молчал.',
      'Из вежливости он спросил водителя, давно ли тот работает ночью, — оказалось, двадцать два года.',
      'Водитель был инженером на закрывшемся заводе и собирался таксовать полгода.',
      'В его рассказе не было горечи: он говорил о годах как о собственном выборе.',
      'Игорь не помнит его лица, но помнит руки на руле и эту интонацию.',
    ],
    modelRetelling:
      'A man took a taxi to the airport early in the morning and after a silent start asked the driver how long he had worked at night. The driver said twenty-two years. He had been an engineer before his factory closed and planned to drive for only six months. He spoke about his life without bitterness, told him about his daughter and about knowing every road in the region. At the airport the passenger could only say thank you, and he still remembers the conversation.',
    discussion: [
      'Have you ever had a memorable conversation with a stranger?',
      'Do you usually talk to taxi drivers, or do you prefer silence?',
      'Why do you think people are honest with strangers?',
    ],
    glossary: {
      awake: { t: 'проснувшийся' },
      indicator: { t: 'поворотник' },
      polite: { t: 'вежливый' },
      engineer: { t: 'инженер' },
      factory: { t: 'завод' },
      nineties: { t: 'девяностые' },
      proper: { t: 'нормальный, подходящий' },
      bitterness: { t: 'горечь' },
      navigator: { t: 'навигатор' },
      useless: { t: 'бесполезный' },
      skill: { t: 'навык' },
      proud: { t: 'гордый' },
      passengers: { t: 'пассажиры', l: 'passenger' },
      drunk: { t: 'пьяный' },
      assumed: { t: 'полагали', l: 'assume' },
      paid: { t: 'заплатил', l: 'pay' },
      adequate: { t: 'подходящий, уместный' },
      wheel: { t: 'руль' },
      described: { t: 'описал', l: 'describe' },
      chosen: { t: 'выбранный', l: 'choose' },
      stranger: { t: 'незнакомец' },
      plainly: { t: 'просто, без прикрас' },
      return: { t: 'ответ', n: 'in return — в ответ' },
    },
  },
];
