/** Тексты 2–5. Формат описан в content/index.js. */
export default [
  {
    id: 'ten-pages',
    title: 'Ten Pages a Day',
    topic: 'привычка, которая строится годами',
    genre: { id: 'motivation', label: 'Мотивация', emoji: '🌱' },
    imagePrompt: 'a worn book and a cup of tea on a kitchen table in early morning light',
    paragraphs: [
      '**Everyone wants to change their life in a month. Almost nobody wants to change it in ten minutes a day.** Ivan decided to read more in January. He bought six books, put them on the shelf where he could see them, and told his friends about his plan. By the middle of February the books were still there, still new, and Ivan had stopped talking about them.',
      'The following autumn he tried again, but this time he made the goal almost embarrassing: ten pages a day. Not a chapter. Not thirty minutes. Ten pages, and if he was tired, he could read them badly. The first week felt like nothing at all. He kept waiting for the moment when it would become serious, and that moment never came. Twice he closed the book after eight pages and felt guilty, and both times he opened it again the next evening instead of giving up for the year.',
      'That was exactly why it worked. A small promise is easy to keep on a bad day, and bad days are the ones that break big promises. Ivan read on the bus, in the queue at the bank, for four minutes before sleep. Some days he read eleven pages, some days exactly ten. Nobody noticed. There was nothing to notice. He did not photograph the covers, he did not count the days, and he told nobody at all, which turned out to be part of the method.',
      'A year later he counted: nineteen books. He had not become a different person, and he still did not read every single day. But something quiet had changed. He now finished things. When a task was boring in the middle, he no longer believed that being bored meant he had chosen wrong.',
      '**Big plans are exciting for a week. Small ones are boring for a year and then they surprise you. Choose the promise you can keep on your worst day, not the one that sounds best on your best one.**',
    ],
    questions: [
      {
        question: 'What happened to the six books Ivan bought in January?',
        options: ['He read them all', 'He gave them away', 'They stayed on the shelf', 'He sold them'],
        correctIndex: 2,
        explanation: 'К середине февраля книги стояли на полке нетронутыми.',
      },
      {
        question: 'Why did the small goal work better?',
        options: [
          'It was easy to keep even on a bad day',
          'His friends checked on him',
          'The books were shorter',
          'He had more free time',
        ],
        correctIndex: 0,
        explanation: 'Маленькое обещание легко сдержать в плохой день, а именно плохие дни ломают большие планы.',
      },
      {
        question: 'What did Ivan notice about himself after a year?',
        options: [
          'He became a completely different person',
          'He read every single day',
          'He started finishing things',
          'He stopped watching films',
        ],
        correctIndex: 2,
        explanation: 'Он не стал другим человеком, но начал доводить дела до конца.',
      },
      {
        question: 'What is the main idea of the text?',
        options: [
          'Reading is better than other hobbies',
          'A promise you can always keep beats an impressive one',
          'You should tell friends about your plans',
          'Nineteen books a year is the right target',
        ],
        correctIndex: 1,
        explanation: 'Финал: выбирайте обещание, которое сдержите в худший день, а не то, что красиво звучит.',
      },
    ],
    keyPoints: [
      'В январе Иван решил больше читать, купил шесть книг — и не прочитал ни одной.',
      'Осенью он поставил смешную по размеру цель: десять страниц в день.',
      'Маленькое обещание легко сдержать даже в плохой день — поэтому оно и сработало.',
      'Он читал в автобусе, в очереди, перед сном; за год вышло девятнадцать книг.',
      'Главное изменение — он стал доводить начатое до конца.',
    ],
    modelRetelling:
      'The text is about a man who wanted to read more. In January he bought six books and told everyone about his plan, but he never started. In autumn he tried again with a very small goal: ten pages a day. It was so easy that he could do it even when he was tired, so he never stopped. After a year he had read nineteen books, and he also learned to finish things he had started.',
    discussion: [
      'Have you ever started a new habit in January? What happened?',
      'Do you prefer big goals or small daily steps? Why?',
      'What is one small thing you could do every day to improve your English?',
    ],
    glossary: {
      pages: { t: 'страницы', l: 'page' },
      shelf: { t: 'полка' },
      middle: { t: 'середина' },
      following: { t: 'следующий', l: 'follow' },
      goal: { t: 'цель' },
      embarrassing: { t: 'неловкий, стыдноватый' },
      chapter: { t: 'глава' },
      badly: { t: 'плохо' },
      serious: { t: 'серьёзный' },
      exactly: { t: 'именно, точно' },
      promise: { t: 'обещание' },
      queue: { t: 'очередь', n: 'британское слово; в США — line' },
      counted: { t: 'посчитал', l: 'count' },
      nineteen: { t: 'девятнадцать' },
      quiet: { t: 'тихий, незаметный' },
      task: { t: 'задача' },
      bored: { t: 'скучающий', l: 'bore' },
      chosen: { t: 'выбрал', l: 'choose' },
      exciting: { t: 'воодушевляющий' },
      surprise: { t: 'удивлять' },
      worst: { t: 'худший' },
    },
  },

  {
    id: 'keys-neighbour',
    title: 'The Neighbour With the Keys',
    topic: 'сосед, с которым не здоровались',
    genre: { id: 'life', label: 'Из жизни', emoji: '☕' },
    imagePrompt: 'a narrow apartment staircase with a hallway light and two closed doors',
    paragraphs: [
      '**For six years Anna shared a wall with a man whose name she did not know.** He lived in flat 34, she lived in 35. They met in the lift perhaps twice a month, said nothing, and looked at their phones until the doors opened. Once he held the door for her when she was carrying shopping bags. She said thank you. That was the longest conversation they ever had.',
      'In November her mother became ill in another city, and Anna left in a hurry. She was already on the train when she understood that she had locked her cat inside the flat with food for two days, not for two weeks. She called three friends. All of them lived far away, and one of them was abroad.',
      'Then she remembered the keys. Two years earlier, after a problem with a water pipe, she had given a spare set to the neighbour in 34, and he had given her his. They had done it the way people sign a paper: quickly, politely, without talking about it again. She had not thought about those keys since.',
      'She wrote him a message through the building chat. He answered in four minutes. For eleven days he fed her cat, changed the water, sent short photos with no text, and refused money in a single word. When Anna came back, she brought him a box of chocolates and finally asked his name. It was Sergei. They talked for twenty minutes on the landing, and both of them were surprised how much there was to say.',
      '**People often think that closeness comes first and help comes after. Sometimes it happens the other way round: you help a stranger, and only then find out who they are.**',
    ],
    questions: [
      {
        question: 'How well did Anna know her neighbour before November?',
        options: [
          'They were good friends',
          'They had never met',
          'They met sometimes but never really talked',
          'They worked together',
        ],
        correctIndex: 2,
        explanation: 'Они встречались в лифте пару раз в месяц и почти не разговаривали.',
      },
      {
        question: 'Why was the cat a problem?',
        options: [
          'It was ill',
          'It had food for two days, not two weeks',
          'It ran away',
          'It was afraid of strangers',
        ],
        correctIndex: 1,
        explanation: 'Анна оставила еды на два дня, а уехала на две недели.',
      },
      {
        question: 'Why did the neighbour have her keys?',
        options: [
          'He was the building manager',
          'They exchanged spare keys after a problem with a pipe',
          'She lost hers once',
          'He was a friend of her mother',
        ],
        correctIndex: 1,
        explanation: 'Двумя годами раньше, после аварии с трубой, они обменялись запасными ключами.',
      },
      {
        question: 'What is the main idea of the last paragraph?',
        options: [
          'You should always lock your door',
          'Neighbours are usually unfriendly',
          'Help can come before friendship, not after it',
          'Cats need special care',
        ],
        correctIndex: 2,
        explanation: 'Иногда сначала помощь, и только потом знакомство.',
      },
    ],
    keyPoints: [
      'Шесть лет Анна жила рядом с соседом и не знала его имени.',
      'Ей срочно пришлось уехать к больной матери, а кот остался с едой на два дня.',
      'Она вспомнила, что два года назад они с соседом обменялись запасными ключами.',
      'Одиннадцать дней он кормил кота, присылал фото и отказался от денег.',
      'Вернувшись, Анна узнала его имя — Сергей — и они впервые поговорили.',
    ],
    modelRetelling:
      'The story is about Anna and her neighbour. They lived next to each other for six years but never talked. When Anna had to travel to her sick mother, her cat was left alone with food for only two days. She remembered that she and the neighbour had exchanged spare keys after a water pipe problem. He fed the cat for eleven days and did not take any money. When she came back, she learned that his name was Sergei.',
    discussion: [
      'Do you know your neighbours? How often do you speak to them?',
      'Would you give a spare key to somebody living next door? Why or why not?',
      'Has a stranger ever helped you when you really needed it?',
    ],
    glossary: {
      shared: { t: 'делила (общую)', l: 'share' },
      wall: { t: 'стена' },
      flat: { t: 'квартира', n: 'британское слово; в США — apartment' },
      perhaps: { t: 'возможно' },
      held: { t: 'придержал', l: 'hold' },
      carrying: { t: 'несла', l: 'carry' },
      shopping: { t: 'покупки' },
      bags: { t: 'сумки', l: 'bag' },
      conversation: { t: 'разговор' },
      ill: { t: 'больна' },
      hurry: { t: 'спешка', n: 'in a hurry — в спешке' },
      locked: { t: 'заперла', l: 'lock' },
      abroad: { t: 'за границей' },
      spare: { t: 'запасной' },
      pipe: { t: 'труба' },
      politely: { t: 'вежливо' },
      fed: { t: 'кормил', l: 'feed' },
      refused: { t: 'отказался', l: 'refuse' },
      chocolates: { t: 'конфеты' },
      landing: { t: 'лестничная площадка' },
      closeness: { t: 'близость' },
      stranger: { t: 'незнакомец' },
    },
  },

  {
    id: 'forget-dreams',
    title: 'Why We Forget Our Dreams',
    topic: 'почему сны исчезают через минуту',
    genre: { id: 'science', label: 'Научпоп', emoji: '🔬' },
    imagePrompt: 'a quiet bedroom at dawn, soft grey light on an empty pillow, minimal and calm',
    paragraphs: [
      '**You can live through a whole story at night and lose it in the ninety seconds after you open your eyes.** Almost everyone dreams, several times each night. Yet most people remember almost nothing, and even a strong dream usually disappears before breakfast. This is not a problem with your memory. It is closer to a design choice.',
      'To keep a memory, the brain has to move it from short-term storage into long-term storage. This work depends on certain chemicals, and during the deepest sleep the levels of those chemicals are very low. In other words, while you are dreaming, the part of the brain that normally says "save this" is mostly switched off. The dream happens, but nothing writes it down. This is why a dream can feel completely real for twenty minutes and leave nothing behind but a mood you cannot explain.',
      'There is a second reason, and it is about shape. We remember stories with a clear order: this happened, then that, and it mattered because of this. Dreams break all of those rules. A room becomes a train, a stranger becomes your brother, and time moves sideways. Your memory has nowhere to attach such material, so it slips away like water through open fingers. Try telling somebody a dream at breakfast and you will feel it happening: the story becomes thinner with every sentence, and by the end you are describing a feeling rather than an event.',
      'This also explains a familiar trick. People who keep a notebook by the bed and write immediately after waking begin to remember far more within two or three weeks. They are not dreaming differently. They are simply catching the dream in the short window before it goes, and giving it the one thing it lacked: a written shape.',
      '**So the strange thing is not that we forget our dreams. It is that a machine which usually saves everything decides, every night, that this particular film is not worth keeping.**',
    ],
    questions: [
      {
        question: 'According to the text, why are dreams hard to remember?',
        options: [
          'People sleep too little',
          'The brain chemicals needed to save memories are very low during deep sleep',
          'Dreams are not real events',
          'The brain is too busy at night',
        ],
        correctIndex: 1,
        explanation: 'Во втором абзаце: во время глубокого сна уровень нужных веществ очень низкий.',
      },
      {
        question: 'What is the second reason given in the text?',
        options: [
          'Dreams have no clear order or logic',
          'Dreams are too short',
          'People do not want to remember them',
          'Dreams happen only once a night',
        ],
        correctIndex: 0,
        explanation: 'Сны ломают привычный порядок событий, и памяти не за что зацепиться.',
      },
      {
        question: 'What happens to people who write their dreams down immediately?',
        options: [
          'They sleep better',
          'They start dreaming more often',
          'They begin to remember much more',
          'They stop dreaming',
        ],
        correctIndex: 2,
        explanation: 'За две-три недели они начинают вспоминать заметно больше — сны при этом те же.',
      },
      {
        question: 'How does the writer describe forgetting dreams?',
        options: [
          'As a fault in the brain',
          'As an illness',
          'As something close to a design choice',
          'As a modern problem',
        ],
        correctIndex: 2,
        explanation: 'В первом абзаце: это не сбой памяти, а скорее устройство системы.',
      },
    ],
    keyPoints: [
      'Люди видят сны каждую ночь, но почти ничего не помнят уже через полторы минуты после пробуждения.',
      'Чтобы запомнить, мозгу нужно перенести информацию в долговременную память — а во сне нужных веществ почти нет.',
      'Вторая причина: у снов нет понятного порядка событий, памяти не за что зацепиться.',
      'Если записывать сны сразу после пробуждения, через пару недель начинаешь помнить гораздо больше.',
      'Удивительно не то, что мы забываем сны, а то, что мозг каждую ночь решает их не сохранять.',
    ],
    modelRetelling:
      'The text explains why people forget their dreams. First, the brain needs certain chemicals to save memories, and during deep sleep these chemicals are very low, so the dream is never written down. Second, dreams have no clear order, and our memory finds it hard to keep something without a shape. If you write your dreams down as soon as you wake up, you can remember much more after a few weeks.',
    discussion: [
      'Do you usually remember your dreams? How often?',
      'Have you ever tried keeping a notebook by your bed?',
      'Do you think dreams mean something, or are they just noise?',
    ],
    glossary: {
      whole: { t: 'целый' },
      ninety: { t: 'девяносто' },
      seconds: { t: 'секунды', l: 'second' },
      several: { t: 'несколько' },
      disappears: { t: 'исчезает', l: 'disappear' },
      design: { t: 'устройство, замысел' },
      choice: { t: 'выбор' },
      storage: { t: 'хранилище' },
      depends: { t: 'зависит', l: 'depend' },
      certain: { t: 'определённые' },
      chemicals: { t: 'вещества', l: 'chemical' },
      deepest: { t: 'самый глубокий', l: 'deep' },
      levels: { t: 'уровни', l: 'level' },
      switched: { t: 'выключен', l: 'switch', n: 'switched off — отключён' },
      shape: { t: 'форма' },
      order: { t: 'порядок' },
      mattered: { t: 'имело значение', l: 'matter' },
      rules: { t: 'правила', l: 'rule' },
      sideways: { t: 'вбок' },
      attach: { t: 'прикрепить' },
      slips: { t: 'ускользает', l: 'slip' },
      fingers: { t: 'пальцы', l: 'finger' },
      familiar: { t: 'знакомый' },
      trick: { t: 'приём, хитрость' },
      immediately: { t: 'сразу же' },
      waking: { t: 'пробуждение', l: 'wake' },
      catching: { t: 'ловят', l: 'catch' },
      lacked: { t: 'не хватало', l: 'lack' },
      particular: { t: 'конкретный' },
      worth: { t: 'стоящий' },
    },
  },

  {
    id: 'wrong-glass',
    title: 'The Glass on the Wrong Side',
    topic: 'разбитое окно и одна лишняя деталь',
    genre: { id: 'mystery', label: 'Детектив', emoji: '🔎' },
    imagePrompt: 'a broken shop window at night, glass on the pavement, blue police light, noir mood',
    paragraphs: [
      '**Every liar leaves something behind, and it is almost never the thing they were worried about.** The shop on Green Street was robbed on Sunday night. The owner, Mr Kaminski, called the police at seven in the morning and met them at the door in his coat, still holding his car keys. The window at the back was broken, the till was empty, and a laptop was gone.',
      'Detective Rivas walked around the room twice without saying anything. Mr Kaminski explained that thieves had come in through the back window during the night, taken the money and the laptop, and left the same way. He had lost about two thousand pounds, he said, and the insurance company already had the papers. He said this twice, in the same words, as people do when they have practised a sentence in the car.',
      'Rivas asked one question: had anyone touched the window since the morning? No, said Mr Kaminski, nobody at all. The detective nodded and looked at the floor under the window for a long moment. Then she asked her second question, which was not about the window: how long had the shop been losing money? Mr Kaminski said something about the new supermarket on the corner, and then stopped in the middle of the sentence.',
      'When a window is broken from outside, the glass falls inside the room. Under this window there was almost no glass on the floor. On the wet pavement outside, however, there was plenty of it, in small bright pieces around the wall. Somebody had stood in the shop and pushed the glass out into the street.',
      '**Mr Kaminski sat down slowly on a box beside the counter. He had thought about the money, the laptop and the papers for the insurance. He had not thought for one second about which way glass falls.**',
    ],
    questions: [
      {
        question: 'What did Mr Kaminski say had happened?',
        options: [
          'He had lost his keys',
          'Thieves came in through the back window at night',
          'A customer stole the laptop',
          'The shop caught fire',
        ],
        correctIndex: 1,
        explanation: 'Он рассказал, что воры влезли ночью через заднее окно.',
      },
      {
        question: 'Where was most of the broken glass?',
        options: ['Inside, under the window', 'On the counter', 'Outside on the pavement', 'In the till'],
        correctIndex: 2,
        explanation: 'Внутри стекла почти не было, зато снаружи на мокром тротуаре его было много.',
      },
      {
        question: 'Why does this detail matter?',
        options: [
          'Glass falls inside when a window is broken from outside',
          'The pavement was wet',
          'The glass was very small',
          'Thieves usually clean up',
        ],
        correctIndex: 0,
        explanation: 'Если бьют снаружи, стекло летит внутрь — значит, окно выбили из магазина.',
      },
      {
        question: 'What does the detective suspect?',
        options: [
          'A customer is guilty',
          'The police made a mistake',
          'The owner staged the robbery himself',
          'Nothing was actually stolen from the till',
        ],
        correctIndex: 2,
        explanation: 'Её второй вопрос — давно ли магазин в убытке — намекает на страховку и инсценировку.',
      },
    ],
    keyPoints: [
      'В воскресенье ночью ограбили магазин на Грин-стрит.',
      'Хозяин, мистер Камински, сказал, что воры влезли через заднее окно и унесли деньги и ноутбук.',
      'Детектив Ривас заметила, что стекла почти нет внутри, зато много снаружи на тротуаре.',
      'Если окно бьют снаружи, стекло падает внутрь — значит, его выбили изнутри.',
      'Второй вопрос детектива — давно ли магазин теряет деньги — указывает на страховку.',
    ],
    modelRetelling:
      'A shop was robbed on Sunday night, and the owner told the police that thieves had broken the back window and taken the money and a laptop. The detective noticed that there was almost no glass inside the shop, but a lot of glass outside on the pavement. When a window is broken from outside, the glass falls inside, so somebody must have broken it from inside the shop. The detective then asked whether the shop had been losing money, which suggests the owner did it for the insurance.',
    discussion: [
      'Do you enjoy detective stories? What makes a good one?',
      'Have you ever noticed a small detail that changed how you saw a situation?',
      'What do you think will happen to Mr Kaminski next?',
    ],
    glossary: {
      liar: { t: 'лжец' },
      behind: { t: 'позади', n: 'leave behind — оставлять после себя' },
      robbed: { t: 'ограблен', l: 'rob' },
      owner: { t: 'владелец' },
      coat: { t: 'пальто' },
      broken: { t: 'разбитый', l: 'break' },
      till: { t: 'касса' },
      laptop: { t: 'ноутбук' },
      gone: { t: 'исчез', l: 'go' },
      detective: { t: 'детектив' },
      thieves: { t: 'воры', l: 'thief' },
      insurance: { t: 'страховка' },
      papers: { t: 'документы', l: 'paper' },
      touched: { t: 'трогал', l: 'touch' },
      nodded: { t: 'кивнула', l: 'nod' },
      pavement: { t: 'тротуар' },
      plenty: { t: 'много' },
      pieces: { t: 'кусочки', l: 'piece' },
      pushed: { t: 'вытолкнул', l: 'push' },
      counter: { t: 'прилавок' },
      pounds: { t: 'фунты', l: 'pound' },
      guilty: { t: 'виновный' },
    },
  },
];
